package tw.com.mitac.thp.bean;

// Generated 2016/8/4 上午 11:08:46 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BhsCollaborationFeedback generated by hbm2java
 */
@Entity
@Table(name = "bhs_collaboration_feedback", catalog = "thp")
public class BhsCollaborationFeedback implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String parentSysid;
	private Date feedbackTime;
	private String feedbackDetail;
	private String backMemberSysid;
	private String memberSysid;

	public BhsCollaborationFeedback() {
	}

	public BhsCollaborationFeedback(String sysid, String creator, String creationDate, String operator,
			String operationDate, String parentSysid, Date feedbackTime, String feedbackDetail) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.parentSysid = parentSysid;
		this.feedbackTime = feedbackTime;
		this.feedbackDetail = feedbackDetail;
	}

	public BhsCollaborationFeedback(String sysid, String creator, String creationDate, String operator,
			String operationDate, String parentSysid, Date feedbackTime, String feedbackDetail, String backMemberSysid,
			String memberSysid) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.parentSysid = parentSysid;
		this.feedbackTime = feedbackTime;
		this.feedbackDetail = feedbackDetail;
		this.backMemberSysid = backMemberSysid;
		this.memberSysid = memberSysid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "COLLABORATION_SYSID", nullable = false, length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEEDBACK_TIME", nullable = false, length = 19)
	public Date getFeedbackTime() {
		return this.feedbackTime;
	}

	public void setFeedbackTime(Date feedbackTime) {
		this.feedbackTime = feedbackTime;
	}

	@Column(name = "FEEDBACK_DETAIL", nullable = false, length = 65535)
	public String getFeedbackDetail() {
		return this.feedbackDetail;
	}

	public void setFeedbackDetail(String feedbackDetail) {
		this.feedbackDetail = feedbackDetail;
	}

	@Column(name = "BACK_MEMBER_SYSID", length = 45)
	public String getBackMemberSysid() {
		return this.backMemberSysid;
	}

	public void setBackMemberSysid(String backMemberSysid) {
		this.backMemberSysid = backMemberSysid;
	}

	@Column(name = "MEMBER_SYSID", length = 45)
	public String getMemberSysid() {
		return this.memberSysid;
	}

	public void setMemberSysid(String memberSysid) {
		this.memberSysid = memberSysid;
	}

}
