package tw.com.mitac.thp.bean;
// Generated 2016/6/10 �U�� 04:55:05 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BhsCollaborationId generated by hbm2java
 */
@Embeddable
public class BhsCollaborationId implements java.io.Serializable {

	private String sysid;
	private String siteMemberSysid;

	public BhsCollaborationId() {
	}

	public BhsCollaborationId(String sysid, String siteMemberSysid) {
		this.sysid = sysid;
		this.siteMemberSysid = siteMemberSysid;
	}

	@Column(name = "SYSID", nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "SITE_MEMBER_SYSID", nullable = false, length = 45)
	public String getSiteMemberSysid() {
		return this.siteMemberSysid;
	}

	public void setSiteMemberSysid(String siteMemberSysid) {
		this.siteMemberSysid = siteMemberSysid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BhsCollaborationId))
			return false;
		BhsCollaborationId castOther = (BhsCollaborationId) other;

		return ((this.getSysid() == castOther.getSysid()) || (this.getSysid() != null && castOther.getSysid() != null
				&& this.getSysid().equals(castOther.getSysid())))
				&& ((this.getSiteMemberSysid() == castOther.getSiteMemberSysid())
						|| (this.getSiteMemberSysid() != null && castOther.getSiteMemberSysid() != null
								&& this.getSiteMemberSysid().equals(castOther.getSiteMemberSysid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSysid() == null ? 0 : this.getSysid().hashCode());
		result = 37 * result + (getSiteMemberSysid() == null ? 0 : this.getSiteMemberSysid().hashCode());
		return result;
	}

}
