package tw.com.mitac.thp.bean;

// Generated 2016/11/22 上午 10:51:03 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BhsCollaboration generated by hbm2java
 */
@Entity
@Table(name = "bhs_collaboration", catalog = "thp")
public class BhsCollaboration implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String sourceId;
	private String collaborationStatus;
	private String collaborationNo;
	private String collaborationName;
	private String collaborationTitle;
	private String countryCode;
	private String collaborationPhone;
	private String countryCode2;
	private String reservePhone;
	private String collaborationMail;
	private String collaborationCompany;
	private String collaborationUnit;
	private String collaborationCountry;
	private String collaborationCompanyCountry;
	private String collaborationCompanyAreaCode;
	private String collaborationAddr;
	private String collaborationWebsite;
	private String collaborationBus;
	private String collaborationDescribe;
	private String siteMemberSysid;
	private Date collaborationVideoOneLocal;
	private Date collaborationVideoOneTaiwan;
	private Date collaborationVideoTwoLocal;
	private Date collaborationVideoTwoTaiwan;
	private String interestTechnologySysid;
	private String proposeTechnologyMenuSysid;
	private String interestProductsSysid;
	private String proposeProductsMenuSysid;
	private String interestHighlightSysid;
	private String interestOther;
	private Boolean isRead;
	
	private java.util.Set<BhsCollaborationFeedback> detailSet;

	public java.util.Set<BhsCollaborationFeedback> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<BhsCollaborationFeedback> detailSet) {
		this.detailSet = detailSet;
	}

	public BhsCollaboration() {
	}

	public BhsCollaboration(String sysid, String creator, String creationDate, String operator, String operationDate,
			String sourceId, String collaborationStatus, String collaborationNo, String collaborationName,
			String collaborationPhone, String collaborationMail, String collaborationCompany,
			String collaborationCountry, String collaborationDescribe, String siteMemberSysid, Boolean isRead) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.sourceId = sourceId;
		this.collaborationStatus = collaborationStatus;
		this.collaborationNo = collaborationNo;
		this.collaborationName = collaborationName;
		this.collaborationPhone = collaborationPhone;
		this.collaborationMail = collaborationMail;
		this.collaborationCompany = collaborationCompany;
		this.collaborationCountry = collaborationCountry;
		this.collaborationDescribe = collaborationDescribe;
		this.siteMemberSysid = siteMemberSysid;
		this.isRead = isRead;
	}

	public BhsCollaboration(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String sourceId, String collaborationStatus, String collaborationNo,
			String collaborationName, String collaborationTitle, String countryCode, String collaborationPhone,
			String countryCode2, String reservePhone, String collaborationMail, String collaborationCompany,
			String collaborationUnit, String collaborationCountry, String collaborationCompanyCountry,
			String collaborationCompanyAreaCode, String collaborationAddr, String collaborationWebsite,
			String collaborationBus, String collaborationDescribe, String siteMemberSysid,
			Date collaborationVideoOneLocal, Date collaborationVideoOneTaiwan, Date collaborationVideoTwoLocal,
			Date collaborationVideoTwoTaiwan, String interestTechnologySysid, String proposeTechnologyMenuSysid,
			String interestProductsSysid, String proposeProductsMenuSysid, String interestHighlightSysid,
			String interestOther, Boolean isRead) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.sourceId = sourceId;
		this.collaborationStatus = collaborationStatus;
		this.collaborationNo = collaborationNo;
		this.collaborationName = collaborationName;
		this.collaborationTitle = collaborationTitle;
		this.countryCode = countryCode;
		this.collaborationPhone = collaborationPhone;
		this.countryCode2 = countryCode2;
		this.reservePhone = reservePhone;
		this.collaborationMail = collaborationMail;
		this.collaborationCompany = collaborationCompany;
		this.collaborationUnit = collaborationUnit;
		this.collaborationCountry = collaborationCountry;
		this.collaborationCompanyCountry = collaborationCompanyCountry;
		this.collaborationCompanyAreaCode = collaborationCompanyAreaCode;
		this.collaborationAddr = collaborationAddr;
		this.collaborationWebsite = collaborationWebsite;
		this.collaborationBus = collaborationBus;
		this.collaborationDescribe = collaborationDescribe;
		this.siteMemberSysid = siteMemberSysid;
		this.collaborationVideoOneLocal = collaborationVideoOneLocal;
		this.collaborationVideoOneTaiwan = collaborationVideoOneTaiwan;
		this.collaborationVideoTwoLocal = collaborationVideoTwoLocal;
		this.collaborationVideoTwoTaiwan = collaborationVideoTwoTaiwan;
		this.interestTechnologySysid = interestTechnologySysid;
		this.proposeTechnologyMenuSysid = proposeTechnologyMenuSysid;
		this.interestProductsSysid = interestProductsSysid;
		this.proposeProductsMenuSysid = proposeProductsMenuSysid;
		this.interestHighlightSysid = interestHighlightSysid;
		this.interestOther = interestOther;
		this.isRead = isRead;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SOURCE_ID", nullable = false)
	public String getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "COLLABORATION_STATUS", nullable = false, length = 20)
	public String getCollaborationStatus() {
		return this.collaborationStatus;
	}

	public void setCollaborationStatus(String collaborationStatus) {
		this.collaborationStatus = collaborationStatus;
	}

	@Column(name = "COLLABORATION_NO", nullable = false, length = 45)
	public String getCollaborationNo() {
		return this.collaborationNo;
	}

	public void setCollaborationNo(String collaborationNo) {
		this.collaborationNo = collaborationNo;
	}

	@Column(name = "COLLABORATION_NAME", nullable = false)
	public String getCollaborationName() {
		return this.collaborationName;
	}

	public void setCollaborationName(String collaborationName) {
		this.collaborationName = collaborationName;
	}

	@Column(name = "COLLABORATION_TITLE")
	public String getCollaborationTitle() {
		return this.collaborationTitle;
	}

	public void setCollaborationTitle(String collaborationTitle) {
		this.collaborationTitle = collaborationTitle;
	}

	@Column(name = "COUNTRY_CODE", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "COLLABORATION_PHONE", nullable = false)
	public String getCollaborationPhone() {
		return this.collaborationPhone;
	}

	public void setCollaborationPhone(String collaborationPhone) {
		this.collaborationPhone = collaborationPhone;
	}

	@Column(name = "COUNTRY_CODE2", length = 10)
	public String getCountryCode2() {
		return this.countryCode2;
	}

	public void setCountryCode2(String countryCode2) {
		this.countryCode2 = countryCode2;
	}

	@Column(name = "RESERVE_PHONE")
	public String getReservePhone() {
		return this.reservePhone;
	}

	public void setReservePhone(String reservePhone) {
		this.reservePhone = reservePhone;
	}

	@Column(name = "COLLABORATION_MAIL", nullable = false)
	public String getCollaborationMail() {
		return this.collaborationMail;
	}

	public void setCollaborationMail(String collaborationMail) {
		this.collaborationMail = collaborationMail;
	}

	@Column(name = "COLLABORATION_COMPANY", nullable = false)
	public String getCollaborationCompany() {
		return this.collaborationCompany;
	}

	public void setCollaborationCompany(String collaborationCompany) {
		this.collaborationCompany = collaborationCompany;
	}

	@Column(name = "COLLABORATION_UNIT")
	public String getCollaborationUnit() {
		return this.collaborationUnit;
	}

	public void setCollaborationUnit(String collaborationUnit) {
		this.collaborationUnit = collaborationUnit;
	}

	@Column(name = "COLLABORATION_COUNTRY", nullable = false)
	public String getCollaborationCountry() {
		return this.collaborationCountry;
	}

	public void setCollaborationCountry(String collaborationCountry) {
		this.collaborationCountry = collaborationCountry;
	}

	@Column(name = "COLLABORATION_COMPANY_COUNTRY")
	public String getCollaborationCompanyCountry() {
		return this.collaborationCompanyCountry;
	}

	public void setCollaborationCompanyCountry(String collaborationCompanyCountry) {
		this.collaborationCompanyCountry = collaborationCompanyCountry;
	}

	@Column(name = "COLLABORATION_COMPANY_AREA_CODE")
	public String getCollaborationCompanyAreaCode() {
		return this.collaborationCompanyAreaCode;
	}

	public void setCollaborationCompanyAreaCode(String collaborationCompanyAreaCode) {
		this.collaborationCompanyAreaCode = collaborationCompanyAreaCode;
	}

	@Column(name = "COLLABORATION_ADDR")
	public String getCollaborationAddr() {
		return this.collaborationAddr;
	}

	public void setCollaborationAddr(String collaborationAddr) {
		this.collaborationAddr = collaborationAddr;
	}

	@Column(name = "COLLABORATION_WEBSITE")
	public String getCollaborationWebsite() {
		return this.collaborationWebsite;
	}

	public void setCollaborationWebsite(String collaborationWebsite) {
		this.collaborationWebsite = collaborationWebsite;
	}

	@Column(name = "COLLABORATION_BUS")
	public String getCollaborationBus() {
		return this.collaborationBus;
	}

	public void setCollaborationBus(String collaborationBus) {
		this.collaborationBus = collaborationBus;
	}

	@Column(name = "COLLABORATION_DESCRIBE", nullable = false)
	public String getCollaborationDescribe() {
		return this.collaborationDescribe;
	}

	public void setCollaborationDescribe(String collaborationDescribe) {
		this.collaborationDescribe = collaborationDescribe;
	}

	@Column(name = "SITE_MEMBER_SYSID", nullable = false, length = 45)
	public String getSiteMemberSysid() {
		return this.siteMemberSysid;
	}

	public void setSiteMemberSysid(String siteMemberSysid) {
		this.siteMemberSysid = siteMemberSysid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLABORATION_VIDEO_ONE_LOCAL", length = 19)
	public Date getCollaborationVideoOneLocal() {
		return this.collaborationVideoOneLocal;
	}

	public void setCollaborationVideoOneLocal(Date collaborationVideoOneLocal) {
		this.collaborationVideoOneLocal = collaborationVideoOneLocal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLABORATION_VIDEO_ONE_TAIWAN", length = 19)
	public Date getCollaborationVideoOneTaiwan() {
		return this.collaborationVideoOneTaiwan;
	}

	public void setCollaborationVideoOneTaiwan(Date collaborationVideoOneTaiwan) {
		this.collaborationVideoOneTaiwan = collaborationVideoOneTaiwan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLABORATION_VIDEO_TWO_LOCAL", length = 19)
	public Date getCollaborationVideoTwoLocal() {
		return this.collaborationVideoTwoLocal;
	}

	public void setCollaborationVideoTwoLocal(Date collaborationVideoTwoLocal) {
		this.collaborationVideoTwoLocal = collaborationVideoTwoLocal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLABORATION_VIDEO_TWO_TAIWAN", length = 19)
	public Date getCollaborationVideoTwoTaiwan() {
		return this.collaborationVideoTwoTaiwan;
	}

	public void setCollaborationVideoTwoTaiwan(Date collaborationVideoTwoTaiwan) {
		this.collaborationVideoTwoTaiwan = collaborationVideoTwoTaiwan;
	}

	@Column(name = "INTEREST_TECHNOLOGY_SYSID", length = 65535)
	public String getInterestTechnologySysid() {
		return this.interestTechnologySysid;
	}

	public void setInterestTechnologySysid(String interestTechnologySysid) {
		this.interestTechnologySysid = interestTechnologySysid;
	}

	@Column(name = "PROPOSE_TECHNOLOGY_MENU_SYSID", length = 65535)
	public String getProposeTechnologyMenuSysid() {
		return this.proposeTechnologyMenuSysid;
	}

	public void setProposeTechnologyMenuSysid(String proposeTechnologyMenuSysid) {
		this.proposeTechnologyMenuSysid = proposeTechnologyMenuSysid;
	}

	@Column(name = "INTEREST_PRODUCTS_SYSID", length = 65535)
	public String getInterestProductsSysid() {
		return this.interestProductsSysid;
	}

	public void setInterestProductsSysid(String interestProductsSysid) {
		this.interestProductsSysid = interestProductsSysid;
	}

	@Column(name = "PROPOSE_PRODUCTS_MENU_SYSID", length = 65535)
	public String getProposeProductsMenuSysid() {
		return this.proposeProductsMenuSysid;
	}

	public void setProposeProductsMenuSysid(String proposeProductsMenuSysid) {
		this.proposeProductsMenuSysid = proposeProductsMenuSysid;
	}

	@Column(name = "INTEREST_HIGHLIGHT_SYSID", length = 65535)
	public String getInterestHighlightSysid() {
		return this.interestHighlightSysid;
	}

	public void setInterestHighlightSysid(String interestHighlightSysid) {
		this.interestHighlightSysid = interestHighlightSysid;
	}

	@Column(name = "INTEREST_OTHER")
	public String getInterestOther() {
		return this.interestOther;
	}

	public void setInterestOther(String interestOther) {
		this.interestOther = interestOther;
	}

	@Column(name = "IS_READ", nullable = false)
	public Boolean getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

}
