package tw.com.mitac.thp.bean;

// Generated 2016/3/25 下午 03:00:48 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BhsOrders generated by hbm2java
 */
@Entity
@Table(name = "bhs_orders", catalog = "thp")
public class BhsOrders implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String billno;
	private Date issueDate;
	private String sourceType;
	private String vendorSysid;
	private String orderType;
	private String memberSysid;
	private String memberPositionSysid;
	private String memberVendorSysid;
	private String duns;
	private String businessType;
	private String billStatus;
	private String ordersItem;
	private String ordersDetail;
	private Set<BhsOrdersFeedback> detailSet;

	public Set<BhsOrdersFeedback> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(Set<BhsOrdersFeedback> detailSet) {
		this.detailSet = detailSet;
	}

	public BhsOrders() {
	}

	public BhsOrders(String sysid, String creator, String creationDate, String operator, String operationDate,
			String billno) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.billno = billno;
	}

	public BhsOrders(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String billno, Date issueDate, String sourceType, String vendorSysid, String orderType,
			String memberSysid, String memberPositionSysid, String memberVendorSysid, String duns, String businessType,
			String billStatus, String ordersItem, String ordersDetail) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.billno = billno;
		this.issueDate = issueDate;
		this.sourceType = sourceType;
		this.vendorSysid = vendorSysid;
		this.orderType = orderType;
		this.memberSysid = memberSysid;
		this.memberPositionSysid = memberPositionSysid;
		this.memberVendorSysid = memberVendorSysid;
		this.duns = duns;
		this.businessType = businessType;
		this.billStatus = billStatus;
		this.ordersItem = ordersItem;
		this.ordersDetail = ordersDetail;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ODNO", nullable = false, length = 45)
	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_DATE", length = 10)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "SOURCE_TYPE")
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "VENDOR_SYSID", length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "ORDER_TYPE", length = 45)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "MEMBER_SYSID", length = 45)
	public String getMemberSysid() {
		return this.memberSysid;
	}

	public void setMemberSysid(String memberSysid) {
		this.memberSysid = memberSysid;
	}

	@Column(name = "MEMBER_POSITION_SYSID", length = 45)
	public String getMemberPositionSysid() {
		return this.memberPositionSysid;
	}

	public void setMemberPositionSysid(String memberPositionSysid) {
		this.memberPositionSysid = memberPositionSysid;
	}

	@Column(name = "MEMBER_VENDOR_SYSID", length = 45)
	public String getMemberVendorSysid() {
		return this.memberVendorSysid;
	}

	public void setMemberVendorSysid(String memberVendorSysid) {
		this.memberVendorSysid = memberVendorSysid;
	}

	@Column(name = "DUNS", length = 45)
	public String getDuns() {
		return this.duns;
	}

	public void setDuns(String duns) {
		this.duns = duns;
	}

	@Column(name = "BUSINESS_TYPE", length = 45)
	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	@Column(name = "ORDERS_STATUS", length = 10)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "ORDERS_ITEM", length = 65535)
	public String getOrdersItem() {
		return this.ordersItem;
	}

	public void setOrdersItem(String ordersItem) {
		this.ordersItem = ordersItem;
	}

	@Column(name = "ORDERS_DETAIL", length = 65535)
	public String getOrdersDetail() {
		return this.ordersDetail;
	}

	public void setOrdersDetail(String ordersDetail) {
		this.ordersDetail = ordersDetail;
	}

}
