package tw.com.mitac.thp.bean;

// Generated 2016/7/18 下午 03:09:09 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BhsRecommandLink generated by hbm2java
 */
@Entity
@Table(name = "bhs_recommand_link", catalog = "thp")
public class BhsRecommandLink implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String recommandLinkName;
	private Boolean isEnabled;
	private String recommandSysid;
	private Integer dataOrder;
	private java.util.Set<BhsRecommandItem> detailSet;

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RECOMMAND_LINK_NAME", nullable = false)
	public String getRecommandLinkName() {
		return this.recommandLinkName;
	}

	public void setRecommandLinkName(String recommandLinkName) {
		this.recommandLinkName = recommandLinkName;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "RECOMMAND_SYSID", length = 45)
	public String getRecommandSysid() {
		return this.recommandSysid;
	}

	public void setRecommandSysid(String recommandSysid) {
		this.recommandSysid = recommandSysid;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	public java.util.Set<BhsRecommandItem> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<BhsRecommandItem> detailSet) {
		this.detailSet = detailSet;
	}
}
