package tw.com.mitac.thp.bean;
// Generated 2016/11/9 �U�� 03:42:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BhsTechnology generated by hbm2java
 */
@Entity
@Table(name = "bhs_technology", catalog = "thp")
public class BhsTechnology implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private Integer dataOrder;
	private Boolean isEnabled;
	private String name;
	private String vendorSysid;
	private String technologySummary;
	private String technologyProfileFull;
	private String technologyText2;
	private String technologyText3;
	private String technologyText4;
	private String technologySummaryImg;

	private java.util.Set<BhsInfoLink> detailSet;
	private java.util.Set<BhsAdsC> detailSet2;

	public java.util.Set<BhsInfoLink> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<BhsInfoLink> detailSet) {
		this.detailSet = detailSet;
	}

	public java.util.Set<BhsAdsC> getDetailSet2() {
		return detailSet2;
	}

	public void setDetailSet2(java.util.Set<BhsAdsC> detailSet2) {
		this.detailSet2 = detailSet2;
	}

	public BhsTechnology() {
	}

	public BhsTechnology(String sysid, String creator, String creationDate, String operator, String operationDate,
			Integer dataOrder, Boolean isEnabled, String name, String vendorSysid) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.name = name;
		this.vendorSysid = vendorSysid;
	}

	public BhsTechnology(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, Integer dataOrder, Boolean isEnabled, String name, String vendorSysid,
			String technologySummary, String technologyProfileFull, String technologyText2, String technologyText3,
			String technologyText4, String technologySummaryImg) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.name = name;
		this.vendorSysid = vendorSysid;
		this.technologySummary = technologySummary;
		this.technologyProfileFull = technologyProfileFull;
		this.technologyText2 = technologyText2;
		this.technologyText3 = technologyText3;
		this.technologyText4 = technologyText4;
		this.technologySummaryImg = technologySummaryImg;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "TECHNOLOGY_NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "TECHNOLOGY_SUMMARY")
	public String getTechnologySummary() {
		return this.technologySummary;
	}

	public void setTechnologySummary(String technologySummary) {
		this.technologySummary = technologySummary;
	}

	@Column(name = "TECHNOLOGY_PROFILE_FULL", length = 65535)
	public String getTechnologyProfileFull() {
		return this.technologyProfileFull;
	}

	public void setTechnologyProfileFull(String technologyProfileFull) {
		this.technologyProfileFull = technologyProfileFull;
	}

	@Column(name = "TECHNOLOGY_TEXT_2", length = 65535)
	public String getTechnologyText2() {
		return this.technologyText2;
	}

	public void setTechnologyText2(String technologyText2) {
		this.technologyText2 = technologyText2;
	}

	@Column(name = "TECHNOLOGY_TEXT_3", length = 65535)
	public String getTechnologyText3() {
		return this.technologyText3;
	}

	public void setTechnologyText3(String technologyText3) {
		this.technologyText3 = technologyText3;
	}

	@Column(name = "TECHNOLOGY_TEXT_4", length = 65535)
	public String getTechnologyText4() {
		return this.technologyText4;
	}

	public void setTechnologyText4(String technologyText4) {
		this.technologyText4 = technologyText4;
	}

	@Column(name = "TECHNOLOGY_SUMMARY_IMG")
	public String getTechnologySummaryImg() {
		return this.technologySummaryImg;
	}

	public void setTechnologySummaryImg(String technologySummaryImg) {
		this.technologySummaryImg = technologySummaryImg;
	}

}
