package tw.com.mitac.thp.bean;

// Generated 2016/3/23 下午 04:17:59 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BhsVendorMore generated by hbm2java
 */
@Entity
@Table(name = "bhs_vendor_more", catalog = "thp")
public class BhsVendorMore implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String recommandTitle;
	private Date recommandStartDate;
	private Date recommandEndDate;
	private Integer recommandOrder;
	private Boolean isEnabled;
	private Set<BhsVendorMoreItem> detailSet;

	public Set<BhsVendorMoreItem> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(Set<BhsVendorMoreItem> detailSet) {
		this.detailSet = detailSet;
	}

	public BhsVendorMore() {
	}

	public BhsVendorMore(String sysid, String creator, String creationDate, String operator, String remark,
			String recommandTitle, Integer recommandOrder, Boolean isEnabled) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.remark = remark;
		this.recommandTitle = recommandTitle;
		this.recommandOrder = recommandOrder;
		this.isEnabled = isEnabled;
	}

	public BhsVendorMore(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String recommandTitle, Date recommandStartDate, Date recommandEndDate,
			Integer recommandOrder, Boolean isEnabled) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.recommandTitle = recommandTitle;
		this.recommandStartDate = recommandStartDate;
		this.recommandEndDate = recommandEndDate;
		this.recommandOrder = recommandOrder;
		this.isEnabled = isEnabled;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE")
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RECOMMAND_TITLE", nullable = false)
	public String getRecommandTitle() {
		return this.recommandTitle;
	}

	public void setRecommandTitle(String recommandTitle) {
		this.recommandTitle = recommandTitle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RECOMMAND_START_DATE", length = 10)
	public Date getRecommandStartDate() {
		return this.recommandStartDate;
	}

	public void setRecommandStartDate(Date recommandStartDate) {
		this.recommandStartDate = recommandStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RECOMMAND_END_DATE", length = 10)
	public Date getRecommandEndDate() {
		return this.recommandEndDate;
	}

	public void setRecommandEndDate(Date recommandEndDate) {
		this.recommandEndDate = recommandEndDate;
	}

	@Column(name = "RECOMMAND_ORDER", nullable = false)
	public Integer getRecommandOrder() {
		return this.recommandOrder;
	}

	public void setRecommandOrder(Integer recommandOrder) {
		this.recommandOrder = recommandOrder;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

}
