package tw.com.mitac.thp.bean;

// Generated 2016/4/19 下午 07:54:37 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsAdvertisement generated by hbm2java
 */
@Entity
@Table(name = "cps_advertisement", catalog = "thp")
public class CpsAdvertisement implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String entitySysid;
	private String dataId;
	private String name;
	private String filePath;
	private String pricingType;
	private String broadcastingType;
	private Long maxAmount;
	private BigDecimal unitPrice;
	private Long eachMaxRentDay;
	private Boolean isEnabled;

	public CpsAdvertisement() {
	}

	public CpsAdvertisement(String sysid, String creator, String creationDate, String operator, String operationDate,
			String entitySysid, String dataId, String name, String pricingType, String broadcastingType,
			Long maxAmount, BigDecimal unitPrice, Long eachMaxRentDay, Boolean isEnabled) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.entitySysid = entitySysid;
		this.dataId = dataId;
		this.name = name;
		this.pricingType = pricingType;
		this.broadcastingType = broadcastingType;
		this.maxAmount = maxAmount;
		this.unitPrice = unitPrice;
		this.eachMaxRentDay = eachMaxRentDay;
		this.isEnabled = isEnabled;
	}

	public CpsAdvertisement(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String entitySysid, String dataId, String name, String filePath, String pricingType,
			String broadcastingType, Long maxAmount, BigDecimal unitPrice, Long eachMaxRentDay, Boolean isEnabled) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.dataId = dataId;
		this.name = name;
		this.filePath = filePath;
		this.pricingType = pricingType;
		this.broadcastingType = broadcastingType;
		this.maxAmount = maxAmount;
		this.unitPrice = unitPrice;
		this.eachMaxRentDay = eachMaxRentDay;
		this.isEnabled = isEnabled;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ENTITY_SYSID", nullable = false, length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "ADVERTISEMENT_ID", nullable = false, length = 30)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "ADVERTISEMENT_NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FILE_PATH")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "PRICING_TYPE", nullable = false, length = 50)
	public String getPricingType() {
		return this.pricingType;
	}

	public void setPricingType(String pricingType) {
		this.pricingType = pricingType;
	}

	@Column(name = "BROADCASTING_TYPE", nullable = false, length = 50)
	public String getBroadcastingType() {
		return this.broadcastingType;
	}

	public void setBroadcastingType(String broadcastingType) {
		this.broadcastingType = broadcastingType;
	}

	@Column(name = "MAX_AMOUNT", nullable = false, precision = 13, scale = 0)
	public Long getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(Long maxAmount) {
		this.maxAmount = maxAmount;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 21, scale = 8)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "EACH_MAX_RENT_DAY", nullable = false, precision = 13, scale = 0)
	public Long getEachMaxRentDay() {
		return this.eachMaxRentDay;
	}

	public void setEachMaxRentDay(Long eachMaxRentDay) {
		this.eachMaxRentDay = eachMaxRentDay;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

}
