package tw.com.mitac.thp.bean;

// Generated 2016/4/20 下午 05:39:04 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsAdvertisementRent generated by hbm2java
 */
@Entity
@Table(name = "cps_advertisement_rent", catalog = "thp")
public class CpsAdvertisementRent implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String billno;
	private String billStatus;
	private Date issueDate;
	private String issueMemberSysid;
	private Date closeDate;
	private String entitySysid;
	private String vendorSysid;
	private String advertisementSysid;
	private String advertisementTitle;
	private Date startDate;
	private Date endDate;
	private BigDecimal unitPrice;
	private BigDecimal totalAmount;
	private String filePath;
	private String sourceType;
	private String sourceSysid;
	private String payStatus;
	private String invoiceNo;

	public CpsAdvertisementRent() {
	}

	public CpsAdvertisementRent(String sysid, String creator, String creationDate, String operator,
			String operationDate, String billno, String billStatus, Date issueDate, String issueMemberSysid,
			String entitySysid, String vendorSysid, String advertisementSysid, String advertisementTitle,
			Date startDate, Date endDate, BigDecimal unitPrice, BigDecimal totalAmount, String filePath,
			String payStatus) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.billno = billno;
		this.billStatus = billStatus;
		this.issueDate = issueDate;
		this.issueMemberSysid = issueMemberSysid;
		this.entitySysid = entitySysid;
		this.vendorSysid = vendorSysid;
		this.advertisementSysid = advertisementSysid;
		this.advertisementTitle = advertisementTitle;
		this.startDate = startDate;
		this.endDate = endDate;
		this.unitPrice = unitPrice;
		this.totalAmount = totalAmount;
		this.filePath = filePath;
		this.payStatus = payStatus;
	}

	public CpsAdvertisementRent(String sysid, String creator, String creationDate, String operator,
			String operationDate, String remark, String billno, String billStatus, Date issueDate,
			String issueMemberSysid, Date closeDate, String entitySysid, String vendorSysid, String advertisementSysid,
			String advertisementTitle, Date startDate, Date endDate, BigDecimal unitPrice, BigDecimal totalAmount,
			String filePath, String sourceType, String sourceSysid, String payStatus, String invoiceNo) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.billno = billno;
		this.billStatus = billStatus;
		this.issueDate = issueDate;
		this.issueMemberSysid = issueMemberSysid;
		this.closeDate = closeDate;
		this.entitySysid = entitySysid;
		this.vendorSysid = vendorSysid;
		this.advertisementSysid = advertisementSysid;
		this.advertisementTitle = advertisementTitle;
		this.startDate = startDate;
		this.endDate = endDate;
		this.unitPrice = unitPrice;
		this.totalAmount = totalAmount;
		this.filePath = filePath;
		this.sourceType = sourceType;
		this.sourceSysid = sourceSysid;
		this.payStatus = payStatus;
		this.invoiceNo = invoiceNo;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "BRNO", nullable = false, length = 30)
	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	@Column(name = "BILL_STATUS", nullable = false, length = 10)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ISSUE_DATE", nullable = false, length = 19)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "ISSUE_MEMBER_SYSID", nullable = false, length = 45)
	public String getIssueMemberSysid() {
		return this.issueMemberSysid;
	}

	public void setIssueMemberSysid(String issueMemberSysid) {
		this.issueMemberSysid = issueMemberSysid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLOSE_DATE", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Column(name = "ENTITY_SYSID", nullable = false, length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "ADVERTISEMENT_SYSID", nullable = false, length = 45)
	public String getAdvertisementSysid() {
		return this.advertisementSysid;
	}

	public void setAdvertisementSysid(String advertisementSysid) {
		this.advertisementSysid = advertisementSysid;
	}

	@Column(name = "ADVERTISEMENT_TITLE", nullable = false)
	public String getAdvertisementTitle() {
		return this.advertisementTitle;
	}

	public void setAdvertisementTitle(String advertisementTitle) {
		this.advertisementTitle = advertisementTitle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 21, scale = 8)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 21, scale = 8)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "FILE_PATH", nullable = false)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "SOURCE_TYPE")
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "SOURCE_SYSID", length = 45)
	public String getSourceSysid() {
		return this.sourceSysid;
	}

	public void setSourceSysid(String sourceSysid) {
		this.sourceSysid = sourceSysid;
	}

	@Column(name = "PAY_STATUS", nullable = false, length = 50)
	public String getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	@Column(name = "INVOICE_NO", length = 10)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

}
