package tw.com.mitac.thp.bean;

// Generated 2016/6/14 下午 01:21:49 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsClickHistory generated by hbm2java
 */
@Entity
@Table(name = "cps_click_history", catalog = "thp")
public class CpsClickHistory implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private String countrySysid;
	private String gender;
	private Date birthday;
	private Integer age;
	private String entityType;
	private String vendorSysid;
	private String favouriteType;
	private String sourceSysid;

	public CpsClickHistory() {
	}

	public CpsClickHistory(String sysid, String creationDate, String creator, String operator, String operationDate,
			String entityType, String vendorSysid) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.entityType = entityType;
		this.vendorSysid = vendorSysid;
	}

	public CpsClickHistory(String sysid, String creationDate, String creator, String operator, String operationDate,
			String remark, String countrySysid, String gender, Date birthday, Integer age, String entityType,
			String vendorSysid, String favouriteType, String sourceSysid) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.countrySysid = countrySysid;
		this.gender = gender;
		this.birthday = birthday;
		this.age = age;
		this.entityType = entityType;
		this.vendorSysid = vendorSysid;
		this.favouriteType = favouriteType;
		this.sourceSysid = sourceSysid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "COUNTRY_SYSID", length = 45)
	public String getCountrySysid() {
		return this.countrySysid;
	}

	public void setCountrySysid(String countrySysid) {
		this.countrySysid = countrySysid;
	}

	@Column(name = "GENDER", length = 30)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDAY", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "ENTITY_TYPE", nullable = false, length = 3)
	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "FAVOURITE_TYPE", length = 2)
	public String getFavouriteType() {
		return this.favouriteType;
	}

	public void setFavouriteType(String favouriteType) {
		this.favouriteType = favouriteType;
	}

	@Column(name = "SOURCE_SYSID", length = 45)
	public String getSourceSysid() {
		return this.sourceSysid;
	}

	public void setSourceSysid(String sourceSysid) {
		this.sourceSysid = sourceSysid;
	}

}
