package tw.com.mitac.thp.bean;

// Generated 2016/10/18 下午 03:37:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsConfig generated by hbm2java
 */
@Entity
@Table(name = "cps_config", catalog = "thp")
public class CpsConfig implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String siteTitle;
	private String siteLogo;
	private String siteAdminEmail;
	private String callCenterEmail;
	private String medicalManagerEmail;
	private String medicalCallCenterEmail;
	private String bioCompaniesManagerEmail;
	private String bioCompaniesCallCenterEmail;
	private String smtpServer;
	private Integer smtpPort;
	private String smtpMailFromPersonal;
	private String smtpAuthUsername;
	private String smtpAuthPassword;
	private String siteMetaKeywords;
	private String siteMetaDescription;
	private String indexDesc1;
	private String indexDesc2;
	private String aboutUs;
	private String privacyPolicy;
	private String termsService;

	public CpsConfig() {
	}

	public CpsConfig(String sysid, String creator, String creationDate, String operator, String operationDate,
			Integer smtpPort) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.smtpPort = smtpPort;
	}

	public CpsConfig(String sysid, String creator, String creationDate, String operator, String operationDate,
			String siteTitle, String siteLogo, String siteAdminEmail, String callCenterEmail,
			String medicalManagerEmail, String medicalCallCenterEmail, String bioCompaniesManagerEmail,
			String bioCompaniesCallCenterEmail, String smtpServer, Integer smtpPort, String smtpMailFromPersonal,
			String smtpAuthUsername, String smtpAuthPassword, String siteMetaKeywords, String siteMetaDescription,
			String indexDesc1, String indexDesc2, String aboutUs, String privacyPolicy, String termsService) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.siteTitle = siteTitle;
		this.siteLogo = siteLogo;
		this.siteAdminEmail = siteAdminEmail;
		this.callCenterEmail = callCenterEmail;
		this.medicalManagerEmail = medicalManagerEmail;
		this.medicalCallCenterEmail = medicalCallCenterEmail;
		this.bioCompaniesManagerEmail = bioCompaniesManagerEmail;
		this.bioCompaniesCallCenterEmail = bioCompaniesCallCenterEmail;
		this.smtpServer = smtpServer;
		this.smtpPort = smtpPort;
		this.smtpMailFromPersonal = smtpMailFromPersonal;
		this.smtpAuthUsername = smtpAuthUsername;
		this.smtpAuthPassword = smtpAuthPassword;
		this.siteMetaKeywords = siteMetaKeywords;
		this.siteMetaDescription = siteMetaDescription;
		this.indexDesc1 = indexDesc1;
		this.indexDesc2 = indexDesc2;
		this.aboutUs = aboutUs;
		this.privacyPolicy = privacyPolicy;
		this.termsService = termsService;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "SITE_TITLE")
	public String getSiteTitle() {
		return this.siteTitle;
	}

	public void setSiteTitle(String siteTitle) {
		this.siteTitle = siteTitle;
	}

	@Column(name = "SITE_LOGO")
	public String getSiteLogo() {
		return this.siteLogo;
	}

	public void setSiteLogo(String siteLogo) {
		this.siteLogo = siteLogo;
	}

	@Column(name = "SITE_ADMIN_EMAIL")
	public String getSiteAdminEmail() {
		return this.siteAdminEmail;
	}

	public void setSiteAdminEmail(String siteAdminEmail) {
		this.siteAdminEmail = siteAdminEmail;
	}

	@Column(name = "CALL_CENTER_EMAIL")
	public String getCallCenterEmail() {
		return this.callCenterEmail;
	}

	public void setCallCenterEmail(String callCenterEmail) {
		this.callCenterEmail = callCenterEmail;
	}

	@Column(name = "MEDICAL_MANAGER_EMAIL")
	public String getMedicalManagerEmail() {
		return this.medicalManagerEmail;
	}

	public void setMedicalManagerEmail(String medicalManagerEmail) {
		this.medicalManagerEmail = medicalManagerEmail;
	}

	@Column(name = "MEDICAL_CALL_CENTER_EMAIL")
	public String getMedicalCallCenterEmail() {
		return this.medicalCallCenterEmail;
	}

	public void setMedicalCallCenterEmail(String medicalCallCenterEmail) {
		this.medicalCallCenterEmail = medicalCallCenterEmail;
	}

	@Column(name = "BIO_COMPANIES_MANAGER_EMAIL")
	public String getBioCompaniesManagerEmail() {
		return this.bioCompaniesManagerEmail;
	}

	public void setBioCompaniesManagerEmail(String bioCompaniesManagerEmail) {
		this.bioCompaniesManagerEmail = bioCompaniesManagerEmail;
	}

	@Column(name = "BIO_COMPANIES_CALL_CENTER_EMAIL")
	public String getBioCompaniesCallCenterEmail() {
		return this.bioCompaniesCallCenterEmail;
	}

	public void setBioCompaniesCallCenterEmail(String bioCompaniesCallCenterEmail) {
		this.bioCompaniesCallCenterEmail = bioCompaniesCallCenterEmail;
	}

	@Column(name = "SMTP_SERVER")
	public String getSmtpServer() {
		return this.smtpServer;
	}

	public void setSmtpServer(String smtpServer) {
		this.smtpServer = smtpServer;
	}

	@Column(name = "SMTP_PORT", nullable = false)
	public Integer getSmtpPort() {
		return this.smtpPort;
	}

	public void setSmtpPort(Integer smtpPort) {
		this.smtpPort = smtpPort;
	}

	@Column(name = "SMTP_MAIL_FROM_EMAIL")
	public String getSmtpMailFromPersonal() {
		return this.smtpMailFromPersonal;
	}

	public void setSmtpMailFromPersonal(String smtpMailFromPersonal) {
		this.smtpMailFromPersonal = smtpMailFromPersonal;
	}

	@Column(name = "SMTP_AUTH_USERNAME")
	public String getSmtpAuthUsername() {
		return this.smtpAuthUsername;
	}

	public void setSmtpAuthUsername(String smtpAuthUsername) {
		this.smtpAuthUsername = smtpAuthUsername;
	}

	@Column(name = "SMTP_AUTH_PASSWORD")
	public String getSmtpAuthPassword() {
		return this.smtpAuthPassword;
	}

	public void setSmtpAuthPassword(String smtpAuthPassword) {
		this.smtpAuthPassword = smtpAuthPassword;
	}

	@Column(name = "SITE_META_KEYWORDS")
	public String getSiteMetaKeywords() {
		return this.siteMetaKeywords;
	}

	public void setSiteMetaKeywords(String siteMetaKeywords) {
		this.siteMetaKeywords = siteMetaKeywords;
	}

	@Column(name = "SITE_META_DESCRIPTION", length = 600)
	public String getSiteMetaDescription() {
		return this.siteMetaDescription;
	}

	public void setSiteMetaDescription(String siteMetaDescription) {
		this.siteMetaDescription = siteMetaDescription;
	}

	@Column(name = "INDEX_DESC1")
	public String getIndexDesc1() {
		return this.indexDesc1;
	}

	public void setIndexDesc1(String indexDesc1) {
		this.indexDesc1 = indexDesc1;
	}

	@Column(name = "INDEX_DESC2")
	public String getIndexDesc2() {
		return this.indexDesc2;
	}

	public void setIndexDesc2(String indexDesc2) {
		this.indexDesc2 = indexDesc2;
	}

	@Column(name = "ABOUT_US", length = 65535)
	public String getAboutUs() {
		return this.aboutUs;
	}

	public void setAboutUs(String aboutUs) {
		this.aboutUs = aboutUs;
	}

	@Column(name = "PRIVACY_POLICY", length = 65535)
	public String getPrivacyPolicy() {
		return this.privacyPolicy;
	}

	public void setPrivacyPolicy(String privacyPolicy) {
		this.privacyPolicy = privacyPolicy;
	}

	@Column(name = "TERMS_SERVICE", length = 65535)
	public String getTermsService() {
		return this.termsService;
	}

	public void setTermsService(String termsService) {
		this.termsService = termsService;
	}

}
