package tw.com.mitac.thp.bean;
// Generated 2016/7/20 �U�� 01:50:44 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsEmailTemplate generated by hbm2java
 */
@Entity
@Table(name = "cps_email_template", catalog = "thp")
public class CpsEmailTemplate implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String emailId;
	private String emailTitle;
	private String emailContent;
	private Boolean isSystem;

	public CpsEmailTemplate() {
	}

	public CpsEmailTemplate(String sysid, String creator, String creationDate, String operator, String operationDate,
			String emailId, String emailTitle, String emailContent, Boolean isSystem) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.emailId = emailId;
		this.emailTitle = emailTitle;
		this.emailContent = emailContent;
		this.isSystem = isSystem;
	}

	public CpsEmailTemplate(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String emailId, String emailTitle, String emailContent, Boolean isSystem) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.emailId = emailId;
		this.emailTitle = emailTitle;
		this.emailContent = emailContent;
		this.isSystem = isSystem;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "EMAIL_ID", nullable = false, length = 30)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "EMAIL_TITLE", nullable = false)
	public String getEmailTitle() {
		return this.emailTitle;
	}

	public void setEmailTitle(String emailTitle) {
		this.emailTitle = emailTitle;
	}

	@Column(name = "EMAIL_CONTENT", nullable = false, length = 65535)
	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

	@Column(name = "IS_SYSTEM", nullable = false)
	public Boolean getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(Boolean isSystem) {
		this.isSystem = isSystem;
	}

}
