package tw.com.mitac.thp.bean;
// Generated 2016/11/10 �U�� 03:36:46 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsEpaper generated by hbm2java
 */
@Entity
@Table(name = "cps_epaper", catalog = "thp")
public class CpsEpaper implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String selectObjects;
	private String exceptionObjects;
	private Date publishDate;
	private Date publishDateActual;
	private String sendStatus;
	private String title;
	private String content;
	private java.util.Set<CpsEpaperDetail> detailSet;
	
	public java.util.Set<CpsEpaperDetail> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<CpsEpaperDetail> detailSet) {
		this.detailSet = detailSet;
	}

	public CpsEpaper() {
	}

	public CpsEpaper(String sysid, String creator, String creationDate, String operator, String operationDate,
			String selectObjects, Date publishDate, String title) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.selectObjects = selectObjects;
		this.publishDate = publishDate;
		this.title = title;
	}

	public CpsEpaper(String sysid, String creator, String creationDate, String operator, String operationDate,
			String selectObjects, String exceptionObjects, Date publishDate, Date publishDateActual, String sendStatus,
			String title, String content) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.selectObjects = selectObjects;
		this.exceptionObjects = exceptionObjects;
		this.publishDate = publishDate;
		this.publishDateActual = publishDateActual;
		this.sendStatus = sendStatus;
		this.title = title;
		this.content = content;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "SELECT_OBJECTS", nullable = false)
	public String getSelectObjects() {
		return this.selectObjects;
	}

	public void setSelectObjects(String selectObjects) {
		this.selectObjects = selectObjects;
	}

	@Column(name = "EXCEPTION_OBJECTS")
	public String getExceptionObjects() {
		return this.exceptionObjects;
	}

	public void setExceptionObjects(String exceptionObjects) {
		this.exceptionObjects = exceptionObjects;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUBLISH_DATE", nullable = false, length = 19)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUBLISH_DATE_ACTUAL", length = 19)
	public Date getPublishDateActual() {
		return this.publishDateActual;
	}

	public void setPublishDateActual(Date publishDateActual) {
		this.publishDateActual = publishDateActual;
	}

	@Column(name = "SEND_STATUS")
	public String getSendStatus() {
		return this.sendStatus;
	}

	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
