package tw.com.mitac.thp.bean;

// Generated 2016/4/10 下午 01:06:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsEmailHistory generated by hbm2java
 */
@Entity
@Table(name = "cps_email_history", catalog = "thp")
public class CpsEmailHistory implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String entitySysid;
	private String vendorSysid;
	private String emailAddress;
	private String emailTitle;
	private String emailContent;

	public CpsEmailHistory() {
	}

	public CpsEmailHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			String entitySysid, String emailAddress, String emailTitle, String emailContent) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.entitySysid = entitySysid;
		this.emailAddress = emailAddress;
		this.emailTitle = emailTitle;
		this.emailContent = emailContent;
	}

	public CpsEmailHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String entitySysid, String vendorSysid, String emailAddress, String emailTitle,
			String emailContent) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.vendorSysid = vendorSysid;
		this.emailAddress = emailAddress;
		this.emailTitle = emailTitle;
		this.emailContent = emailContent;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ENTITY_SYSID", nullable = false, length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "VENDOR_SYSID", length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "EMAIL_TITLE", nullable = false)
	public String getEmailTitle() {
		return this.emailTitle;
	}

	public void setEmailTitle(String emailTitle) {
		this.emailTitle = emailTitle;
	}

	@Column(name = "EMAIL_CONTENT", nullable = false, length = 65535)
	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

}
