package tw.com.mitac.thp.bean;
// Generated 2016/6/6 �U�� 05:04:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsExhibitionVendor generated by hbm2java
 */
@Entity
@Table(name = "cps_exhibition_vendor", catalog = "thp")
public class CpsExhibitionVendor implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private Boolean isEnabled;
	private Integer dataOrder;
	private String exhibitionSysid;
	private String exhibitionVendorName;
	private String exhibitionVendorImg;
	private String exhibitionVendorBanner;
	private String exhibitionVendorFile;
	
	private java.util.Set<CpsExhibitionVendorItem> detailSet;

	public java.util.Set<CpsExhibitionVendorItem> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<CpsExhibitionVendorItem> detailSet) {
		this.detailSet = detailSet;
	}

	public CpsExhibitionVendor() {
	}

	public CpsExhibitionVendor(String sysid, String creationDate, String creator, String operator, String operationDate,
			Integer dataOrder, String exhibitionSysid) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.dataOrder = dataOrder;
		this.exhibitionSysid = exhibitionSysid;
	}

	public CpsExhibitionVendor(String sysid, String creationDate, String creator, String operator, String operationDate,
			String remark, Boolean isEnabled, Integer dataOrder, String exhibitionSysid, String exhibitionVendorName,
			String exhibitionVendorImg, String exhibitionVendorBanner, String exhibitionVendorFile) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.isEnabled = isEnabled;
		this.dataOrder = dataOrder;
		this.exhibitionSysid = exhibitionSysid;
		this.exhibitionVendorName = exhibitionVendorName;
		this.exhibitionVendorImg = exhibitionVendorImg;
		this.exhibitionVendorBanner = exhibitionVendorBanner;
		this.exhibitionVendorFile = exhibitionVendorFile;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IS_ENABLED")
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "EXHIBITION_SYSID", nullable = false, length = 45)
	public String getExhibitionSysid() {
		return this.exhibitionSysid;
	}

	public void setExhibitionSysid(String exhibitionSysid) {
		this.exhibitionSysid = exhibitionSysid;
	}

	@Column(name = "EXHIBITION_VENDOR_NAME")
	public String getExhibitionVendorName() {
		return this.exhibitionVendorName;
	}

	public void setExhibitionVendorName(String exhibitionVendorName) {
		this.exhibitionVendorName = exhibitionVendorName;
	}

	@Column(name = "EXHIBITION_VENDOR_IMG")
	public String getExhibitionVendorImg() {
		return this.exhibitionVendorImg;
	}

	public void setExhibitionVendorImg(String exhibitionVendorImg) {
		this.exhibitionVendorImg = exhibitionVendorImg;
	}

	@Column(name = "EXHIBITION_VENDOR_BANNER")
	public String getExhibitionVendorBanner() {
		return this.exhibitionVendorBanner;
	}

	public void setExhibitionVendorBanner(String exhibitionVendorBanner) {
		this.exhibitionVendorBanner = exhibitionVendorBanner;
	}

	@Column(name = "EXHIBITION_VENDOR_FILE")
	public String getExhibitionVendorFile() {
		return this.exhibitionVendorFile;
	}

	public void setExhibitionVendorFile(String exhibitionVendorFile) {
		this.exhibitionVendorFile = exhibitionVendorFile;
	}

}
