package tw.com.mitac.thp.bean;
// Generated 2016/6/13 �U�� 02:09:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsExhibitionVendorItem generated by hbm2java
 */
@Entity
@Table(name = "cps_exhibition_vendor_item", catalog = "thp")
public class CpsExhibitionVendorItem implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private String parentSysid;
	private String vendorDmName;
	private String vendorDmSummary;
	private String exhibitionVendorBimg;
	private String exhibitionVendorSimg;
	private Integer dataOrder;

	public CpsExhibitionVendorItem() {
	}

	public CpsExhibitionVendorItem(String sysid, String creationDate, String creator, String operator,
			String operationDate, Integer dataOrder) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.dataOrder = dataOrder;
	}

	public CpsExhibitionVendorItem(String sysid, String creationDate, String creator, String operator,
			String operationDate, String remark, String parentSysid, String vendorDmName, String vendorDmSummary,
			String exhibitionVendorBimg, String exhibitionVendorSimg, Integer dataOrder) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.parentSysid = parentSysid;
		this.vendorDmName = vendorDmName;
		this.vendorDmSummary = vendorDmSummary;
		this.exhibitionVendorBimg = exhibitionVendorBimg;
		this.exhibitionVendorSimg = exhibitionVendorSimg;
		this.dataOrder = dataOrder;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "EXHIBITION_VENDOR_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "VENDOR_DM_NAME")
	public String getVendorDmName() {
		return this.vendorDmName;
	}

	public void setVendorDmName(String vendorDmName) {
		this.vendorDmName = vendorDmName;
	}

	@Column(name = "VENDOR_DM_SUMMARY")
	public String getVendorDmSummary() {
		return this.vendorDmSummary;
	}

	public void setVendorDmSummary(String vendorDmSummary) {
		this.vendorDmSummary = vendorDmSummary;
	}

	@Column(name = "EXHIBITION_VENDOR_BIMG")
	public String getExhibitionVendorBimg() {
		return this.exhibitionVendorBimg;
	}

	public void setExhibitionVendorBimg(String exhibitionVendorBimg) {
		this.exhibitionVendorBimg = exhibitionVendorBimg;
	}

	@Column(name = "EXHIBITION_VENDOR_SIMG")
	public String getExhibitionVendorSimg() {
		return this.exhibitionVendorSimg;
	}

	public void setExhibitionVendorSimg(String exhibitionVendorSimg) {
		this.exhibitionVendorSimg = exhibitionVendorSimg;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

}
