package tw.com.mitac.thp.bean;
// Generated 2016/9/26 �U�� 04:48:08 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsHottopicInfo generated by hbm2java
 */
@Entity
@Table(name = "cps_hottopic_info", catalog = "thp")
public class CpsHottopicInfo implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private Boolean isEnabled;
	private Integer dataOrder;
	private String hottopicSysid;
	private String hottopicTitle;
	private String hottopicSummary;
	private String hottopicFull;
	private String hottopicImage;

	public CpsHottopicInfo() {
	}

	public CpsHottopicInfo(String sysid, String creator, String creationDate, String operator, String operationDate,
			Boolean isEnabled, Integer dataOrder, String hottopicTitle) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.isEnabled = isEnabled;
		this.dataOrder = dataOrder;
		this.hottopicTitle = hottopicTitle;
	}

	public CpsHottopicInfo(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, Boolean isEnabled, Integer dataOrder, String hottopicSysid, String hottopicTitle,
			String hottopicSummary, String hottopicFull, String hottopicImage) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.isEnabled = isEnabled;
		this.dataOrder = dataOrder;
		this.hottopicSysid = hottopicSysid;
		this.hottopicTitle = hottopicTitle;
		this.hottopicSummary = hottopicSummary;
		this.hottopicFull = hottopicFull;
		this.hottopicImage = hottopicImage;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "HOTTOPIC_SYSID", length = 45)
	public String getHottopicSysid() {
		return this.hottopicSysid;
	}

	public void setHottopicSysid(String hottopicSysid) {
		this.hottopicSysid = hottopicSysid;
	}

	@Column(name = "HOTTOPIC_TITLE", nullable = false)
	public String getHottopicTitle() {
		return this.hottopicTitle;
	}

	public void setHottopicTitle(String hottopicTitle) {
		this.hottopicTitle = hottopicTitle;
	}

	@Column(name = "HOTTOPIC_SUMMARY", length = 500)
	public String getHottopicSummary() {
		return this.hottopicSummary;
	}

	public void setHottopicSummary(String hottopicSummary) {
		this.hottopicSummary = hottopicSummary;
	}

	@Column(name = "HOTTOPIC_FULL", length = 65535)
	public String getHottopicFull() {
		return this.hottopicFull;
	}

	public void setHottopicFull(String hottopicFull) {
		this.hottopicFull = hottopicFull;
	}

	@Column(name = "HOTTOPIC_IMAGE")
	public String getHottopicImage() {
		return this.hottopicImage;
	}

	public void setHottopicImage(String hottopicImage) {
		this.hottopicImage = hottopicImage;
	}

}
