package tw.com.mitac.thp.bean;
// Generated 2016/9/26 �U�� 04:30:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsHottopic generated by hbm2java
 */
@Entity
@Table(name = "cps_hottopic", catalog = "thp")
public class CpsHottopic implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private Integer dataOrder;
	private Boolean isEnabled;
	private String hottopicName;
	private String hottopicName2;
	private String hottopicImg1F;
	private String hottopicImg1B;
	private String hottopicImg2F;
	private String hottopicImg2B;
	private String hottopicImg3F;
	private String hottopicImg3B;
	private String hottopicImg4F;
	private String hottopicImg4B;
	private String hottopicVideoTitle;
	private String hottopicVideoSummary;
	private String hottopicVideoUrl;
	private java.util.Set<CpsHottopicAds> detailSet;
	
	public java.util.Set<CpsHottopicAds> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<CpsHottopicAds> detailSet) {
		this.detailSet = detailSet;
	}

	public CpsHottopic() {
	}

	public CpsHottopic(String sysid, String creator, String creationDate, String operator, String operationDate,
			Integer dataOrder, Boolean isEnabled, String hottopicName, String hottopicName2) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.hottopicName = hottopicName;
		this.hottopicName2 = hottopicName2;
	}

	public CpsHottopic(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, Integer dataOrder, Boolean isEnabled, String hottopicName, String hottopicName2,
			String hottopicImg1F, String hottopicImg1B, String hottopicImg2F, String hottopicImg2B,
			String hottopicImg3F, String hottopicImg3B, String hottopicImg4F, String hottopicImg4B,
			String hottopicVideoTitle, String hottopicVideoSummary, String hottopicVideoUrl) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.hottopicName = hottopicName;
		this.hottopicName2 = hottopicName2;
		this.hottopicImg1F = hottopicImg1F;
		this.hottopicImg1B = hottopicImg1B;
		this.hottopicImg2F = hottopicImg2F;
		this.hottopicImg2B = hottopicImg2B;
		this.hottopicImg3F = hottopicImg3F;
		this.hottopicImg3B = hottopicImg3B;
		this.hottopicImg4F = hottopicImg4F;
		this.hottopicImg4B = hottopicImg4B;
		this.hottopicVideoTitle = hottopicVideoTitle;
		this.hottopicVideoSummary = hottopicVideoSummary;
		this.hottopicVideoUrl = hottopicVideoUrl;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "HOTTOPIC_NAME", nullable = false)
	public String getHottopicName() {
		return this.hottopicName;
	}

	public void setHottopicName(String hottopicName) {
		this.hottopicName = hottopicName;
	}

	@Column(name = "HOTTOPIC_NAME2", nullable = false)
	public String getHottopicName2() {
		return this.hottopicName2;
	}

	public void setHottopicName2(String hottopicName2) {
		this.hottopicName2 = hottopicName2;
	}

	@Column(name = "HOTTOPIC_IMG1_F")
	public String getHottopicImg1F() {
		return this.hottopicImg1F;
	}

	public void setHottopicImg1F(String hottopicImg1F) {
		this.hottopicImg1F = hottopicImg1F;
	}

	@Column(name = "HOTTOPIC_IMG1_B")
	public String getHottopicImg1B() {
		return this.hottopicImg1B;
	}

	public void setHottopicImg1B(String hottopicImg1B) {
		this.hottopicImg1B = hottopicImg1B;
	}

	@Column(name = "HOTTOPIC_IMG2_F")
	public String getHottopicImg2F() {
		return this.hottopicImg2F;
	}

	public void setHottopicImg2F(String hottopicImg2F) {
		this.hottopicImg2F = hottopicImg2F;
	}

	@Column(name = "HOTTOPIC_IMG2_B")
	public String getHottopicImg2B() {
		return this.hottopicImg2B;
	}

	public void setHottopicImg2B(String hottopicImg2B) {
		this.hottopicImg2B = hottopicImg2B;
	}

	@Column(name = "HOTTOPIC_IMG3_F")
	public String getHottopicImg3F() {
		return this.hottopicImg3F;
	}

	public void setHottopicImg3F(String hottopicImg3F) {
		this.hottopicImg3F = hottopicImg3F;
	}

	@Column(name = "HOTTOPIC_IMG3_B")
	public String getHottopicImg3B() {
		return this.hottopicImg3B;
	}

	public void setHottopicImg3B(String hottopicImg3B) {
		this.hottopicImg3B = hottopicImg3B;
	}

	@Column(name = "HOTTOPIC_IMG4_F")
	public String getHottopicImg4F() {
		return this.hottopicImg4F;
	}

	public void setHottopicImg4F(String hottopicImg4F) {
		this.hottopicImg4F = hottopicImg4F;
	}

	@Column(name = "HOTTOPIC_IMG4_B")
	public String getHottopicImg4B() {
		return this.hottopicImg4B;
	}

	public void setHottopicImg4B(String hottopicImg4B) {
		this.hottopicImg4B = hottopicImg4B;
	}

	@Column(name = "HOTTOPIC_VIDEO_TITLE")
	public String getHottopicVideoTitle() {
		return this.hottopicVideoTitle;
	}

	public void setHottopicVideoTitle(String hottopicVideoTitle) {
		this.hottopicVideoTitle = hottopicVideoTitle;
	}

	@Column(name = "HOTTOPIC_VIDEO_SUMMARY", length = 500)
	public String getHottopicVideoSummary() {
		return this.hottopicVideoSummary;
	}

	public void setHottopicVideoSummary(String hottopicVideoSummary) {
		this.hottopicVideoSummary = hottopicVideoSummary;
	}

	@Column(name = "HOTTOPIC_VIDEO_URL")
	public String getHottopicVideoUrl() {
		return this.hottopicVideoUrl;
	}

	public void setHottopicVideoUrl(String hottopicVideoUrl) {
		this.hottopicVideoUrl = hottopicVideoUrl;
	}

}
