package tw.com.mitac.thp.bean;
// Generated 2016/9/26 �U�� 04:48:08 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsHottopicAds generated by hbm2java
 */
@Entity
@Table(name = "cps_hottopic_ads", catalog = "thp")
public class CpsHottopicAds implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String parentSysid;
	private Boolean isEnabled;
	private Integer dataOrder;
	private Boolean adsTw;
	private Boolean adsCn;
	private Boolean adsUs;
	private String adsDisplaySource;
	private String adsImage;

	public CpsHottopicAds() {
	}

	public CpsHottopicAds(String sysid, String creator, String creationDate, String operator, String operationDate,
			Boolean isEnabled, Integer dataOrder, String adsDisplaySource, String adsImage) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.isEnabled = isEnabled;
		this.dataOrder = dataOrder;
		this.adsDisplaySource = adsDisplaySource;
		this.adsImage = adsImage;
	}

	public CpsHottopicAds(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String parentSysid, Boolean isEnabled, Integer dataOrder, Boolean adsTw, Boolean adsCn,
			Boolean adsUs, String adsDisplaySource, String adsImage) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.parentSysid = parentSysid;
		this.isEnabled = isEnabled;
		this.dataOrder = dataOrder;
		this.adsTw = adsTw;
		this.adsCn = adsCn;
		this.adsUs = adsUs;
		this.adsDisplaySource = adsDisplaySource;
		this.adsImage = adsImage;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "HOTTOPIC_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "ADS_TW")
	public Boolean getAdsTw() {
		return this.adsTw;
	}

	public void setAdsTw(Boolean adsTw) {
		this.adsTw = adsTw;
	}

	@Column(name = "ADS_CN")
	public Boolean getAdsCn() {
		return this.adsCn;
	}

	public void setAdsCn(Boolean adsCn) {
		this.adsCn = adsCn;
	}

	@Column(name = "ADS_US")
	public Boolean getAdsUs() {
		return this.adsUs;
	}

	public void setAdsUs(Boolean adsUs) {
		this.adsUs = adsUs;
	}

	@Column(name = "ADS_DISPLAY_SOURCE", nullable = false)
	public String getAdsDisplaySource() {
		return this.adsDisplaySource;
	}

	public void setAdsDisplaySource(String adsDisplaySource) {
		this.adsDisplaySource = adsDisplaySource;
	}

	@Column(name = "ADS_IMAGE", nullable = false)
	public String getAdsImage() {
		return this.adsImage;
	}

	public void setAdsImage(String adsImage) {
		this.adsImage = adsImage;
	}

}
