package tw.com.mitac.thp.bean;
// Generated 2016/11/8 �W�� 10:06:08 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsKeywords generated by hbm2java
 */
@Entity
@Table(name = "cps_keywords", catalog = "thp")
public class CpsKeywords implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String entitySysid;
	private String keywords;
	private Integer initSearchCount;
	private Integer searchCount;

	public CpsKeywords() {
	}

	public CpsKeywords(String sysid, String creator, String creationDate, String operator, String operationDate) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
	}

	public CpsKeywords(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String entitySysid, String keywords, Integer initSearchCount, Integer searchCount) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.keywords = keywords;
		this.initSearchCount = initSearchCount;
		this.searchCount = searchCount;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ENTITY_SYSID", length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "KEYWORDS")
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "INIT_SEARCH_COUNT")
	public Integer getInitSearchCount() {
		return this.initSearchCount;
	}

	public void setInitSearchCount(Integer initSearchCount) {
		this.initSearchCount = initSearchCount;
	}

	@Column(name = "SEARCH_COUNT")
	public Integer getSearchCount() {
		return this.searchCount;
	}

	public void setSearchCount(Integer searchCount) {
		this.searchCount = searchCount;
	}

}
