package tw.com.mitac.thp.bean;
// Generated 2016/7/15 �W�� 10:39:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CpsMemberForVendor generated by hbm2java
 */
@Entity
@Table(name = "cps_member", catalog = "thp", uniqueConstraints = @UniqueConstraint(columnNames = "UUID"))
public class CpsMemberForVendor implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String uuid;
	private String memberName;
	private String password;
	private String email;
	private String sourceType;
	private String parentSysid;
	private Boolean isEnabled;
	private String gender;
	private String phone;
	private String mobilePhone;
	private String languageType;
	private String emailVerifyCode;

	public CpsMemberForVendor() {
	}

	public CpsMemberForVendor(String sysid, String creator, String creationDate, String operator, String operationDate,
			String uuid, String memberName, String password, String email, Boolean isEnabled, String gender,
			String languageType) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.uuid = uuid;
		this.memberName = memberName;
		this.password = password;
		this.email = email;
		this.isEnabled = isEnabled;
		this.gender = gender;
		this.languageType = languageType;
	}

	public CpsMemberForVendor(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String uuid, String memberName, String password, String email, String sourceType,
			String parentSysid, Boolean isEnabled, String gender, String phone, String mobilePhone, String languageType,
			String emailVerifyCode) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.uuid = uuid;
		this.memberName = memberName;
		this.password = password;
		this.email = email;
		this.sourceType = sourceType;
		this.parentSysid = parentSysid;
		this.isEnabled = isEnabled;
		this.gender = gender;
		this.phone = phone;
		this.mobilePhone = mobilePhone;
		this.languageType = languageType;
		this.emailVerifyCode = emailVerifyCode;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "UUID", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "MEMBER_NAME", nullable = false)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "SOURCE_TYPE")
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "SOURCE_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "GENDER", nullable = false, length = 30)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "PHONE")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "MOBILE_PHONE")
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "LANGUAGE_TYPE", nullable = false, length = 50)
	public String getLanguageType() {
		return this.languageType;
	}

	public void setLanguageType(String languageType) {
		this.languageType = languageType;
	}

	@Column(name = "EMAIL_VERIFY_CODE", length = 50)
	public String getEmailVerifyCode() {
		return this.emailVerifyCode;
	}

	public void setEmailVerifyCode(String emailVerifyCode) {
		this.emailVerifyCode = emailVerifyCode;
	}

}
