package tw.com.mitac.thp.bean;

// Generated 2016/3/28 �U�� 05:54:18 by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsMeetingReportDetails generated by hbm2java
 */
@Entity
@Table(name = "cps_meeting_report_details", catalog = "thp")
public class CpsMeetingReportDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String entitySysid;
	private String meetingType;
	private String meetingRoomId;
	private Date meetingDate;
	private Time meetingStartTime;
	private String meetingSubject;
	private String initiatorCpsMemberSysid;
	private Integer meetingSession;
	private String meetingStatus;
	private Integer attendanceNumber;
	private String cpsMeetingSysid;

	public CpsMeetingReportDetails() {
	}

	public CpsMeetingReportDetails(String sysid, String creator, String creationDate, String operator,
			String operationDate, String meetingRoomId) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.meetingRoomId = meetingRoomId;
	}

	public CpsMeetingReportDetails(String sysid, String creator, String creationDate, String operator,
			String operationDate, String remark, String entitySysid, String meetingType, String meetingRoomId,
			Date meetingDate, Time meetingStartTime, String meetingSubject, String initiatorCpsMemberSysid,
			Integer meetingSession, String meetingStatus, Integer attendanceNumber, String cpsMeetingSysid) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.meetingType = meetingType;
		this.meetingRoomId = meetingRoomId;
		this.meetingDate = meetingDate;
		this.meetingStartTime = meetingStartTime;
		this.meetingSubject = meetingSubject;
		this.initiatorCpsMemberSysid = initiatorCpsMemberSysid;
		this.meetingSession = meetingSession;
		this.meetingStatus = meetingStatus;
		this.attendanceNumber = attendanceNumber;
		this.cpsMeetingSysid = cpsMeetingSysid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)	
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)	
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)	
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)	
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "ENTITY_SYSID", length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "MEETING_TYPE", length = 1)	
	public String getMeetingType() {
		return this.meetingType;
	}

	public void setMeetingType(String meetingType) {
		this.meetingType = meetingType;
	}

	@Column(name = "MEETING_ROOM_ID", nullable = false)
	public String getMeetingRoomId() {
		return this.meetingRoomId;
	}

	public void setMeetingRoomId(String meetingRoomId) {
		this.meetingRoomId = meetingRoomId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEETING_DATE", length = 10)	
	public Date getMeetingDate() {
		return this.meetingDate;
	}

	public void setMeetingDate(Date meetingDate) {
		this.meetingDate = meetingDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "MEETING_START_TIME", length = 8)	
	public Time getMeetingStartTime() {
		return this.meetingStartTime;
	}

	public void setMeetingStartTime(Time meetingStartTime) {
		this.meetingStartTime = meetingStartTime;
	}

	@Column(name = "MEETING_SUBJECT")	
	public String getMeetingSubject() {
		return this.meetingSubject;
	}

	public void setMeetingSubject(String meetingSubject) {
		this.meetingSubject = meetingSubject;
	}

	@Column(name = "INITIATOR_CPS_MEMBER_SYSID")	
	public String getInitiatorCpsMemberSysid() {
		return this.initiatorCpsMemberSysid;
	}

	public void setInitiatorCpsMemberSysid(String initiatorCpsMemberSysid) {
		this.initiatorCpsMemberSysid = initiatorCpsMemberSysid;
	}

	@Column(name = "MEETING_SESSION")	
	public Integer getMeetingSession() {
		return this.meetingSession;
	}

	public void setMeetingSession(Integer meetingSession) {
		this.meetingSession = meetingSession;
	}

	@Column(name = "MEETING_STATUS", length = 1)	
	public String getMeetingStatus() {
		return this.meetingStatus;
	}

	public void setMeetingStatus(String meetingStatus) {
		this.meetingStatus = meetingStatus;
	}

	@Column(name = "ATTENDANCE_NUMBER")	
	public Integer getAttendanceNumber() {
		return this.attendanceNumber;
	}

	public void setAttendanceNumber(Integer attendanceNumber) {
		this.attendanceNumber = attendanceNumber;
	}
	@Column(name = "CPS_MEETING_SYSID", length = 45)
	public String getCpsMeetingSysid() {
		return this.cpsMeetingSysid;
	}

	public void setCpsMeetingSysid(String cpsMeetingSysid) {
		this.cpsMeetingSysid = cpsMeetingSysid;
	}

	@Override
	public String toString() {
		return "CpsMeetingReportDetails [sysid=" + sysid + ", creator=" + creator + ", creationDate=" + creationDate
				+ ", operator=" + operator + ", operationDate=" + operationDate + ", remark=" + remark
				+ ", entitySysid=" + entitySysid + ", meetingType=" + meetingType + ", meetingRoomId=" + meetingRoomId
				+ ", meetingDate=" + meetingDate + ", meetingStartTime=" + meetingStartTime + ", meetingSubject="
				+ meetingSubject + ", initiatorCpsMemberSysid=" + initiatorCpsMemberSysid + ", meetingSession="
				+ meetingSession + ", meetingStatus=" + meetingStatus + ", attendanceNumber=" + attendanceNumber
				+ ", cpsMeetingSysid=" + cpsMeetingSysid + "]";
	}

	
}
