package tw.com.mitac.thp.bean;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 2016/3/28 �U�� 05:54:18 by Hibernate Tools 4.3.1

/**
 * CpsMeetingReportDaily generated by hbm2java
 */
@Entity
@Table(name = "cps_meeting_stat", catalog = "thp")
public class CpsMeetingStat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private Date dateStat;
	private String entitySysid;
	private String meetingType;
	private Integer totalMeeting;
	private Integer totalMeetingMinutes;
	private Integer totalParticipants;

	public CpsMeetingStat() {
	}

	public CpsMeetingStat(String sysid, String creator, String creationDate, String operator,
			String operationDate) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
	}

	public CpsMeetingStat(String sysid, String creator, String creationDate, String operator,
			String operationDate, String remark, String entitySysid, String meetingType, Integer totalMeeting,
			Integer totalMeetingMinutes, Integer totalParticipants) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.meetingType = meetingType;
		this.totalMeeting = totalMeeting;
		this.totalMeetingMinutes = totalMeetingMinutes;
		this.totalParticipants = totalParticipants;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)	
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)	
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)	
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)	
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)	
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)	
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_STAT", length = 10)	
	public Date getDateStat() {
		return dateStat;
	}

	public void setDateStat(Date dateStat) {
		this.dateStat = dateStat;
	}

	@Column(name = "ENTITY_SYSID", length = 45)	
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "MEETING_TYPE", length = 1)	
	public String getMeetingType() {
		return this.meetingType;
	}

	public void setMeetingType(String meetingType) {
		this.meetingType = meetingType;
	}

	@Column(name = "TOTAL_MEETING")	
	public Integer getTotalMeeting() {
		return this.totalMeeting;
	}

	public void setTotalMeeting(Integer totalMeeting) {
		this.totalMeeting = totalMeeting;
	}

	@Column(name = "TOTAL_MEETING_MINUTES")	
	public Integer getTotalMeetingMinutes() {
		return this.totalMeetingMinutes;
	}

	public void setTotalMeetingMinutes(Integer totalMeetingMinutes) {
		this.totalMeetingMinutes = totalMeetingMinutes;
	}

	@Column(name = "TOTAL_PARTICIPANTS")	
	public Integer getTotalParticipants() {
		return this.totalParticipants;
	}

	public void setTotalParticipants(Integer totalParticipants) {
		this.totalParticipants = totalParticipants;
	}

	@Override
	public String toString() {
		return "CpsMeetingStat [sysid=" + sysid + ", creator=" + creator + ", creationDate=" + creationDate
				+ ", operator=" + operator + ", operationDate=" + operationDate + ", remark=" + remark
				+ ", entitySysid=" + entitySysid + ", meetingType=" + meetingType + ", totalMeeting=" + totalMeeting
				+ ", totalMeetingMinutes=" + totalMeetingMinutes + ", totalParticipants=" + totalParticipants + "]";
	}

	
}
