package tw.com.mitac.thp.bean;

// Generated 2016/3/17 �U�� 01:40:44 by Hibernate Tools 4.3.1

import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.codec.binary.Hex;

/**
 * CpsMeetingCfg generated by hbm2java
 */
@Entity
@Table(name = "cps_meeting_cfg", catalog = "thp")
public class CpsMeetingCfg implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String accountStr;
	private String passwordStr;
	private String keyStr;
	private String secretStr;
	private String usageEntitySysid;
	private Integer attendance;

	public CpsMeetingCfg() {
	}

	public CpsMeetingCfg(String sysid, String creator, String creationDate,
			String operator, String operationDate, String accountStr) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.accountStr = accountStr;
	}

	public CpsMeetingCfg(String sysid, String creator, String creationDate,
			String operator, String operationDate, String remark,
			String accountStr, String passwordStr, String keyStr,
			String secretStr, String usageEntitySysid, Integer attendance) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.accountStr = accountStr;
		this.passwordStr = passwordStr;
		this.keyStr = keyStr;
		this.secretStr = secretStr;
		this.usageEntitySysid = usageEntitySysid;
		this.attendance = attendance;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ACCOUNT_STR", nullable = false)
	public String getAccountStr() {
		return this.accountStr;
	}

	public void setAccountStr(String accountStr) {
		this.accountStr = accountStr;
	}

	@Column(name = "PASSWORD_STR")
	public String getPasswordStr() {
		return this.passwordStr;
	}

	public void setPasswordStr(String passwordStr) {
		this.passwordStr = passwordStr;
	}

	@Column(name = "KEY_STR")
	public String getKeyStr() {
		return this.keyStr;
	}

	public void setKeyStr(String keyStr) {
		this.keyStr = keyStr;
	}

	@Column(name = "SECRET_STR")
	public String getSecretStr() {
		return this.secretStr;
	}

	public void setSecretStr(String secretStr) {
		this.secretStr = secretStr;
	}

	@Column(name = "USAGE_ENTITY_SYSID")
	public String getUsageEntitySysid() {
		return this.usageEntitySysid;
	}

	public void setUsageEntitySysid(String usageEntitySysid) {
		this.usageEntitySysid = usageEntitySysid;
	}

	@Column(name = "ATTENDANCE")
	public Integer getAttendance() {
		return this.attendance;
	}

	public void setAttendance(Integer attendance) {
		this.attendance = attendance;
	}
	
	public String genCheckValue(Map<String, String> param) {
		
		System.out.println(param);

		List<Map.Entry<String, String>> list = new ArrayList<Map.Entry<String, String>>(param.entrySet());
		
		Collections.sort(list, new Comparator<Map.Entry<String, String>>(){
			public int compare(Map.Entry<String, String> ent1, Map.Entry<String, String> ent2) {
				
				return (ent1.getKey().compareTo(ent2.getKey()));
			}
		});
		
		StringBuffer sb = new StringBuffer();
		
		sb.append("API_Key=").append(keyStr).append("&");
		
		for(Map.Entry<String, String> mapEntry : list) {
			String key = mapEntry.getKey();
			String value = mapEntry.getValue();
			sb.append(key).append("=").append(value).append("&");
		}
		sb.append("API_Secret=").append(secretStr);
		
		String rtn = md5enc(sb.toString().toLowerCase()).toUpperCase();
		
		return rtn;
		
	}
	
	private String md5enc(String s) {
		String rtn = null;
		try {
			MessageDigest md = MessageDigest.getInstance("MD5");			
			byte[] messageDigest = md.digest(s.getBytes());
			rtn = Hex.encodeHexString(messageDigest);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return rtn;
		
	}
	
	public void setTestData() {
		keyStr = "5bc1d22bb1a1be8300602b7a3c63a23b6M0I";
		accountStr = "7e83a128550269d3b8a0990703653e";
		secretStr = "87c32adc2b9fac9fe3a4a775fdb2f2766NM6";
	}

	@Override
	public String toString() {
		return "CpsMeetingCfg [sysid=" + sysid + ", creator=" + creator + ", creationDate=" + creationDate
				+ ", operator=" + operator + ", operationDate=" + operationDate + ", remark=" + remark
				+ ", accountStr=" + accountStr + ", passwordStr=" + passwordStr + ", keyStr=" + keyStr + ", secretStr="
				+ secretStr + ", usageEntitySysid=" + usageEntitySysid + ", attendance=" + attendance + "]";
	}

}
