package tw.com.mitac.thp.bean;

// Generated 2016/10/20 下午 03:54:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsRegistration generated by hbm2java
 */
@Entity
@Table(name = "cps_registration", catalog = "thp")
public class CpsRegistration implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private String siteMemberSysid;
	private Boolean isPay;
	private String registrationType;
	private String entitySysid;
	private String sourceSysid;
	private String registrationMail;
	private String registrationName;
	private String registrationCountry;
	private String registrationCompany;
	private String registrationUnit;
	private String registrationTitle;
	private String registrationTel;
	private String registrationTel2;
	private String registrationCompanyCountrySysid;
	private String registrationCompanyAreaCode;
	private String registrationAddr;
	private String registrationWebsite;
	private String registrationBus;
	private String countryCode;
	private String countryCode2;
	private String registrationCall;
	private String lastName;

	public CpsRegistration() {
	}

	public CpsRegistration(String sysid, String creationDate, String creator, String operator, String operationDate,
			String siteMemberSysid, Boolean isPay, String registrationType, String entitySysid, String sourceSysid) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.siteMemberSysid = siteMemberSysid;
		this.isPay = isPay;
		this.registrationType = registrationType;
		this.entitySysid = entitySysid;
		this.sourceSysid = sourceSysid;
	}

	public CpsRegistration(String sysid, String creationDate, String creator, String operator, String operationDate,
			String remark, String siteMemberSysid, Boolean isPay, String registrationType, String entitySysid,
			String sourceSysid, String registrationMail, String registrationName, String registrationCountry,
			String registrationCompany, String registrationUnit, String registrationTitle, String registrationTel,
			String registrationTel2, String registrationCompanyCountrySysid, String registrationCompanyAreaCode,
			String registrationAddr, String registrationWebsite, String registrationBus, String countryCode,
			String countryCode2, String registrationCall, String lastName) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.siteMemberSysid = siteMemberSysid;
		this.isPay = isPay;
		this.registrationType = registrationType;
		this.entitySysid = entitySysid;
		this.sourceSysid = sourceSysid;
		this.registrationMail = registrationMail;
		this.registrationName = registrationName;
		this.registrationCountry = registrationCountry;
		this.registrationCompany = registrationCompany;
		this.registrationUnit = registrationUnit;
		this.registrationTitle = registrationTitle;
		this.registrationTel = registrationTel;
		this.registrationTel2 = registrationTel2;
		this.registrationCompanyCountrySysid = registrationCompanyCountrySysid;
		this.registrationCompanyAreaCode = registrationCompanyAreaCode;
		this.registrationAddr = registrationAddr;
		this.registrationWebsite = registrationWebsite;
		this.registrationBus = registrationBus;
		this.countryCode = countryCode;
		this.countryCode2 = countryCode2;
		this.registrationCall = registrationCall;
		this.lastName = lastName;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SITE_MEMBER_SYSID", nullable = false, length = 45)
	public String getSiteMemberSysid() {
		return this.siteMemberSysid;
	}

	public void setSiteMemberSysid(String siteMemberSysid) {
		this.siteMemberSysid = siteMemberSysid;
	}

	@Column(name = "IS_PAY", nullable = false)
	public Boolean getIsPay() {
		return this.isPay;
	}

	public void setIsPay(Boolean isPay) {
		this.isPay = isPay;
	}

	@Column(name = "REGISTRATION_TYPE", nullable = false, length = 1)
	public String getRegistrationType() {
		return this.registrationType;
	}

	public void setRegistrationType(String registrationType) {
		this.registrationType = registrationType;
	}

	@Column(name = "ENTITY_SYSID", nullable = false, length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "SOURCE_SYSID", nullable = false, length = 45)
	public String getSourceSysid() {
		return this.sourceSysid;
	}

	public void setSourceSysid(String sourceSysid) {
		this.sourceSysid = sourceSysid;
	}

	@Column(name = "REGISTRATION_MAIL")
	public String getRegistrationMail() {
		return this.registrationMail;
	}

	public void setRegistrationMail(String registrationMail) {
		this.registrationMail = registrationMail;
	}

	@Column(name = "REGISTRATION_NAME")
	public String getRegistrationName() {
		return this.registrationName;
	}

	public void setRegistrationName(String registrationName) {
		this.registrationName = registrationName;
	}

	@Column(name = "REGISTRATION_COUNTRY")
	public String getRegistrationCountry() {
		return this.registrationCountry;
	}

	public void setRegistrationCountry(String registrationCountry) {
		this.registrationCountry = registrationCountry;
	}

	@Column(name = "REGISTRATION_COMPANY")
	public String getRegistrationCompany() {
		return this.registrationCompany;
	}

	public void setRegistrationCompany(String registrationCompany) {
		this.registrationCompany = registrationCompany;
	}

	@Column(name = "REGISTRATION_UNIT")
	public String getRegistrationUnit() {
		return this.registrationUnit;
	}

	public void setRegistrationUnit(String registrationUnit) {
		this.registrationUnit = registrationUnit;
	}

	@Column(name = "REGISTRATION_TITLE")
	public String getRegistrationTitle() {
		return this.registrationTitle;
	}

	public void setRegistrationTitle(String registrationTitle) {
		this.registrationTitle = registrationTitle;
	}

	@Column(name = "REGISTRATION_TEL")
	public String getRegistrationTel() {
		return this.registrationTel;
	}

	public void setRegistrationTel(String registrationTel) {
		this.registrationTel = registrationTel;
	}

	@Column(name = "REGISTRATION_TEL2")
	public String getRegistrationTel2() {
		return this.registrationTel2;
	}

	public void setRegistrationTel2(String registrationTel2) {
		this.registrationTel2 = registrationTel2;
	}

	@Column(name = "REGISTRATION_COMPANY_COUNTRY_SYSID", length = 45)
	public String getRegistrationCompanyCountrySysid() {
		return this.registrationCompanyCountrySysid;
	}

	public void setRegistrationCompanyCountrySysid(String registrationCompanyCountrySysid) {
		this.registrationCompanyCountrySysid = registrationCompanyCountrySysid;
	}

	@Column(name = "REGISTRATION_COMPANY_AREA_CODE", length = 45)
	public String getRegistrationCompanyAreaCode() {
		return this.registrationCompanyAreaCode;
	}

	public void setRegistrationCompanyAreaCode(String registrationCompanyAreaCode) {
		this.registrationCompanyAreaCode = registrationCompanyAreaCode;
	}

	@Column(name = "REGISTRATION_ADDR")
	public String getRegistrationAddr() {
		return this.registrationAddr;
	}

	public void setRegistrationAddr(String registrationAddr) {
		this.registrationAddr = registrationAddr;
	}

	@Column(name = "REGISTRATION_WEBSITE")
	public String getRegistrationWebsite() {
		return this.registrationWebsite;
	}

	public void setRegistrationWebsite(String registrationWebsite) {
		this.registrationWebsite = registrationWebsite;
	}

	@Column(name = "REGISTRATION_BUS")
	public String getRegistrationBus() {
		return this.registrationBus;
	}

	public void setRegistrationBus(String registrationBus) {
		this.registrationBus = registrationBus;
	}

	@Column(name = "COUNTRY_CODE", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "COUNTRY_CODE2", length = 10)
	public String getCountryCode2() {
		return this.countryCode2;
	}

	public void setCountryCode2(String countryCode2) {
		this.countryCode2 = countryCode2;
	}

	@Column(name = "REGISTRATION_CALL")
	public String getRegistrationCall() {
		return this.registrationCall;
	}

	public void setRegistrationCall(String registrationCall) {
		this.registrationCall = registrationCall;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
