package tw.com.mitac.thp.bean;

// Generated 2016/4/25 下午 01:55:57 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsSmsSend generated by hbm2java
 */
@Entity
@Table(name = "cps_sms_send", catalog = "thp")
public class CpsSmsSend implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String smsTenplateSysid;
	private Date smsDateTime;
	private Set<CpsSmsSendDetail> detailSet;

	public Set<CpsSmsSendDetail> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(Set<CpsSmsSendDetail> detailSet) {
		this.detailSet = detailSet;
	}

	public CpsSmsSend() {
	}

	public CpsSmsSend(String sysid, String creator, String creationDate, String operator, String operationDate,
			String smsTenplateSysid) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.smsTenplateSysid = smsTenplateSysid;
	}

	public CpsSmsSend(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String smsTenplateSysid, Date smsDateTime) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.smsTenplateSysid = smsTenplateSysid;
		this.smsDateTime = smsDateTime;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SMS_TENPLATE_SYSID", nullable = false, length = 45)
	public String getSmsTenplateSysid() {
		return this.smsTenplateSysid;
	}

	public void setSmsTenplateSysid(String smsTenplateSysid) {
		this.smsTenplateSysid = smsTenplateSysid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SMS_DATE_TIME", length = 19)
	public Date getSmsDateTime() {
		return this.smsDateTime;
	}

	public void setSmsDateTime(Date smsDateTime) {
		this.smsDateTime = smsDateTime;
	}

}
