package tw.com.mitac.thp.bean;

// Generated 2016/4/26 下午 01:12:46 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CpsSmsSendDetail generated by hbm2java
 */
@Entity
@Table(name = "cps_sms_send_detail", catalog = "thp")
public class CpsSmsSendDetail implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String parentSysid;
	private String memberSysid;
	private String smsTel;

	public CpsSmsSendDetail() {
	}

	public CpsSmsSendDetail(String sysid, String creator, String creationDate, String operator, String operationDate,
			String memberSysid, String smsTel) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.memberSysid = memberSysid;
		this.smsTel = smsTel;
	}

	public CpsSmsSendDetail(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String parentSysid, String memberSysid, String smsTel) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.parentSysid = parentSysid;
		this.memberSysid = memberSysid;
		this.smsTel = smsTel;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SMS_SEND_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "MEMBER_SYSID", nullable = false, length = 45)
	public String getMemberSysid() {
		return this.memberSysid;
	}

	public void setMemberSysid(String memberSysid) {
		this.memberSysid = memberSysid;
	}

	@Column(name = "SMS_TEL", nullable = false, length = 50)
	public String getSmsTel() {
		return this.smsTel;
	}

	public void setSmsTel(String smsTel) {
		this.smsTel = smsTel;
	}

}
