package tw.com.mitac.thp.bean;

// Generated 2016/4/25 下午 01:55:57 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CpsSmsHistory generated by hbm2java
 */
@Entity
@Table(name = "cps_sms_history", catalog = "thp")
public class CpsSmsHistory implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String entitySysid;
	private String vendorSysid;
	private String smsTel;
	private String smsMessage;
	private Date smsDateTime;

	public CpsSmsHistory() {
	}

	public CpsSmsHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			String entitySysid, String vendorSysid, String smsTel, String smsMessage, Date smsDateTime) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.entitySysid = entitySysid;
		this.vendorSysid = vendorSysid;
		this.smsTel = smsTel;
		this.smsMessage = smsMessage;
		this.smsDateTime = smsDateTime;
	}

	public CpsSmsHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String entitySysid, String vendorSysid, String smsTel, String smsMessage, Date smsDateTime) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.entitySysid = entitySysid;
		this.vendorSysid = vendorSysid;
		this.smsTel = smsTel;
		this.smsMessage = smsMessage;
		this.smsDateTime = smsDateTime;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ENTITY_SYSID", nullable = false, length = 45)
	public String getEntitySysid() {
		return this.entitySysid;
	}

	public void setEntitySysid(String entitySysid) {
		this.entitySysid = entitySysid;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "SMS_TEL", nullable = false, length = 50)
	public String getSmsTel() {
		return this.smsTel;
	}

	public void setSmsTel(String smsTel) {
		this.smsTel = smsTel;
	}

	@Column(name = "SMS_MESSAGE", nullable = false)
	public String getSmsMessage() {
		return this.smsMessage;
	}

	public void setSmsMessage(String smsMessage) {
		this.smsMessage = smsMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SMS_DATE_TIME", nullable = false, length = 19)
	public Date getSmsDateTime() {
		return this.smsDateTime;
	}

	public void setSmsDateTime(Date smsDateTime) {
		this.smsDateTime = smsDateTime;
	}

}
