package tw.com.mitac.thp.bean;
// Generated 2016/11/3 �U�� 05:29:48 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MtsAppointment generated by hbm2java
 */
@Entity
@Table(name = "mts_appointment", catalog = "thp")
public class MtsAppointment implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String siteMemberSysid;
	private String appointmentStatus;
	private String appointmentVendor;
	private String appointmentNo;
	private String mtsProductsSysid;
	private String suffererName;
	private String suffererSurname;
	private String suffererGender;
	private Date suffererBirthday;
	private String suffererCountry;
	private String suffererAreaCode;
	private String suffererAddress;
	private String suffererEmail;
	private String suffererPhone;
	private String suffererReservePhone;
	private String medicalSymptomDescribe;
	private Date appointmentDateOneLocal;
	private Date appointmentDateOneTaiwan;
	private Date appointmentDateTwoLocal;
	private Date appointmentDateTwoTaiwan;
	private String appointmentDoctor;
	private Boolean isAcceptMedicalAtTaiwan;
	private String treatmentMechanism;
	private String otherHelps;
	private String greatOperation;
	private String countryCode;
	private String countryCode2;
	private Boolean isRead;
	private java.util.Set<MtsAppointmentCaseLink> detailSet;
	private java.util.Set<MtsAppointmentFileLink> detailSet2;
	private java.util.Set<MtsAppointmentFeedback> detailSet3;
	
	public java.util.Set<MtsAppointmentCaseLink> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(java.util.Set<MtsAppointmentCaseLink> detailSet) {
		this.detailSet = detailSet;
	}

	public java.util.Set<MtsAppointmentFileLink> getDetailSet2() {
		return detailSet2;
	}

	public void setDetailSet2(java.util.Set<MtsAppointmentFileLink> detailSet2) {
		this.detailSet2 = detailSet2;
	}

	public java.util.Set<MtsAppointmentFeedback> getDetailSet3() {
		return detailSet3;
	}

	public void setDetailSet3(java.util.Set<MtsAppointmentFeedback> detailSet3) {
		this.detailSet3 = detailSet3;
	}

	public MtsAppointment() {
	}

	public MtsAppointment(String sysid, String creator, String creationDate, String operator, String operationDate,
			String siteMemberSysid, String appointmentStatus, String appointmentVendor, String appointmentNo,
			String mtsProductsSysid, String suffererName, String suffererSurname, String suffererGender,
			Date suffererBirthday, String suffererCountry, String suffererAddress, String suffererEmail,
			String suffererPhone, String medicalSymptomDescribe, Boolean isRead) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.siteMemberSysid = siteMemberSysid;
		this.appointmentStatus = appointmentStatus;
		this.appointmentVendor = appointmentVendor;
		this.appointmentNo = appointmentNo;
		this.mtsProductsSysid = mtsProductsSysid;
		this.suffererName = suffererName;
		this.suffererSurname = suffererSurname;
		this.suffererGender = suffererGender;
		this.suffererBirthday = suffererBirthday;
		this.suffererCountry = suffererCountry;
		this.suffererAddress = suffererAddress;
		this.suffererEmail = suffererEmail;
		this.suffererPhone = suffererPhone;
		this.medicalSymptomDescribe = medicalSymptomDescribe;
		this.isRead = isRead;
	}

	public MtsAppointment(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String siteMemberSysid, String appointmentStatus, String appointmentVendor,
			String appointmentNo, String mtsProductsSysid, String suffererName, String suffererSurname,
			String suffererGender, Date suffererBirthday, String suffererCountry, String suffererAreaCode,
			String suffererAddress, String suffererEmail, String suffererPhone, String suffererReservePhone,
			String medicalSymptomDescribe, Date appointmentDateOneLocal, Date appointmentDateOneTaiwan,
			Date appointmentDateTwoLocal, Date appointmentDateTwoTaiwan, String appointmentDoctor,
			Boolean isAcceptMedicalAtTaiwan, String treatmentMechanism, String otherHelps, String greatOperation,
			String countryCode, String countryCode2, Boolean isRead) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.siteMemberSysid = siteMemberSysid;
		this.appointmentStatus = appointmentStatus;
		this.appointmentVendor = appointmentVendor;
		this.appointmentNo = appointmentNo;
		this.mtsProductsSysid = mtsProductsSysid;
		this.suffererName = suffererName;
		this.suffererSurname = suffererSurname;
		this.suffererGender = suffererGender;
		this.suffererBirthday = suffererBirthday;
		this.suffererCountry = suffererCountry;
		this.suffererAreaCode = suffererAreaCode;
		this.suffererAddress = suffererAddress;
		this.suffererEmail = suffererEmail;
		this.suffererPhone = suffererPhone;
		this.suffererReservePhone = suffererReservePhone;
		this.medicalSymptomDescribe = medicalSymptomDescribe;
		this.appointmentDateOneLocal = appointmentDateOneLocal;
		this.appointmentDateOneTaiwan = appointmentDateOneTaiwan;
		this.appointmentDateTwoLocal = appointmentDateTwoLocal;
		this.appointmentDateTwoTaiwan = appointmentDateTwoTaiwan;
		this.appointmentDoctor = appointmentDoctor;
		this.isAcceptMedicalAtTaiwan = isAcceptMedicalAtTaiwan;
		this.treatmentMechanism = treatmentMechanism;
		this.otherHelps = otherHelps;
		this.greatOperation = greatOperation;
		this.countryCode = countryCode;
		this.countryCode2 = countryCode2;
		this.isRead = isRead;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SITE_MEMBER_SYSID", nullable = false, length = 45)
	public String getSiteMemberSysid() {
		return this.siteMemberSysid;
	}

	public void setSiteMemberSysid(String siteMemberSysid) {
		this.siteMemberSysid = siteMemberSysid;
	}

	@Column(name = "APPOINTMENT_STATUS", nullable = false, length = 20)
	public String getAppointmentStatus() {
		return this.appointmentStatus;
	}

	public void setAppointmentStatus(String appointmentStatus) {
		this.appointmentStatus = appointmentStatus;
	}

	@Column(name = "APPOINTMENT_VENDOR", nullable = false, length = 45)
	public String getAppointmentVendor() {
		return this.appointmentVendor;
	}

	public void setAppointmentVendor(String appointmentVendor) {
		this.appointmentVendor = appointmentVendor;
	}

	@Column(name = "APPOINTMENT_NO", nullable = false, length = 45)
	public String getAppointmentNo() {
		return this.appointmentNo;
	}

	public void setAppointmentNo(String appointmentNo) {
		this.appointmentNo = appointmentNo;
	}

	@Column(name = "MTS_PRODUCTS_SYSID", nullable = false, length = 65535)
	public String getMtsProductsSysid() {
		return this.mtsProductsSysid;
	}

	public void setMtsProductsSysid(String mtsProductsSysid) {
		this.mtsProductsSysid = mtsProductsSysid;
	}

	@Column(name = "SUFFERER_NAME", nullable = false)
	public String getSuffererName() {
		return this.suffererName;
	}

	public void setSuffererName(String suffererName) {
		this.suffererName = suffererName;
	}

	@Column(name = "SUFFERER_SURNAME", nullable = false)
	public String getSuffererSurname() {
		return this.suffererSurname;
	}

	public void setSuffererSurname(String suffererSurname) {
		this.suffererSurname = suffererSurname;
	}

	@Column(name = "SUFFERER_GENDER", nullable = false, length = 10)
	public String getSuffererGender() {
		return this.suffererGender;
	}

	public void setSuffererGender(String suffererGender) {
		this.suffererGender = suffererGender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUFFERER_BIRTHDAY", nullable = false, length = 10)
	public Date getSuffererBirthday() {
		return this.suffererBirthday;
	}

	public void setSuffererBirthday(Date suffererBirthday) {
		this.suffererBirthday = suffererBirthday;
	}

	@Column(name = "SUFFERER_COUNTRY", nullable = false)
	public String getSuffererCountry() {
		return this.suffererCountry;
	}

	public void setSuffererCountry(String suffererCountry) {
		this.suffererCountry = suffererCountry;
	}

	@Column(name = "SUFFERER_AREA_CODE", length = 45)
	public String getSuffererAreaCode() {
		return this.suffererAreaCode;
	}

	public void setSuffererAreaCode(String suffererAreaCode) {
		this.suffererAreaCode = suffererAreaCode;
	}

	@Column(name = "SUFFERER_ADDRESS", nullable = false)
	public String getSuffererAddress() {
		return this.suffererAddress;
	}

	public void setSuffererAddress(String suffererAddress) {
		this.suffererAddress = suffererAddress;
	}

	@Column(name = "SUFFERER_EMAIL", nullable = false)
	public String getSuffererEmail() {
		return this.suffererEmail;
	}

	public void setSuffererEmail(String suffererEmail) {
		this.suffererEmail = suffererEmail;
	}

	@Column(name = "SUFFERER_PHONE", nullable = false)
	public String getSuffererPhone() {
		return this.suffererPhone;
	}

	public void setSuffererPhone(String suffererPhone) {
		this.suffererPhone = suffererPhone;
	}

	@Column(name = "SUFFERER_RESERVE_PHONE")
	public String getSuffererReservePhone() {
		return this.suffererReservePhone;
	}

	public void setSuffererReservePhone(String suffererReservePhone) {
		this.suffererReservePhone = suffererReservePhone;
	}

	@Column(name = "MEDICAL_SYMPTOM_DESCRIBE", nullable = false, length = 65535)
	public String getMedicalSymptomDescribe() {
		return this.medicalSymptomDescribe;
	}

	public void setMedicalSymptomDescribe(String medicalSymptomDescribe) {
		this.medicalSymptomDescribe = medicalSymptomDescribe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPOINTMENT_DATE_ONE_LOCAL", length = 19)
	public Date getAppointmentDateOneLocal() {
		return this.appointmentDateOneLocal;
	}

	public void setAppointmentDateOneLocal(Date appointmentDateOneLocal) {
		this.appointmentDateOneLocal = appointmentDateOneLocal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPOINTMENT_DATE_ONE_TAIWAN", length = 19)
	public Date getAppointmentDateOneTaiwan() {
		return this.appointmentDateOneTaiwan;
	}

	public void setAppointmentDateOneTaiwan(Date appointmentDateOneTaiwan) {
		this.appointmentDateOneTaiwan = appointmentDateOneTaiwan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPOINTMENT_DATE_TWO_LOCAL", length = 19)
	public Date getAppointmentDateTwoLocal() {
		return this.appointmentDateTwoLocal;
	}

	public void setAppointmentDateTwoLocal(Date appointmentDateTwoLocal) {
		this.appointmentDateTwoLocal = appointmentDateTwoLocal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPOINTMENT_DATE_TWO_TAIWAN", length = 19)
	public Date getAppointmentDateTwoTaiwan() {
		return this.appointmentDateTwoTaiwan;
	}

	public void setAppointmentDateTwoTaiwan(Date appointmentDateTwoTaiwan) {
		this.appointmentDateTwoTaiwan = appointmentDateTwoTaiwan;
	}

	@Column(name = "APPOINTMENT_DOCTOR")
	public String getAppointmentDoctor() {
		return this.appointmentDoctor;
	}

	public void setAppointmentDoctor(String appointmentDoctor) {
		this.appointmentDoctor = appointmentDoctor;
	}

	@Column(name = "IS_ACCEPT_MEDICAL_AT_TAIWAN")
	public Boolean getIsAcceptMedicalAtTaiwan() {
		return this.isAcceptMedicalAtTaiwan;
	}

	public void setIsAcceptMedicalAtTaiwan(Boolean isAcceptMedicalAtTaiwan) {
		this.isAcceptMedicalAtTaiwan = isAcceptMedicalAtTaiwan;
	}

	@Column(name = "TREATMENT_MECHANISM")
	public String getTreatmentMechanism() {
		return this.treatmentMechanism;
	}

	public void setTreatmentMechanism(String treatmentMechanism) {
		this.treatmentMechanism = treatmentMechanism;
	}

	@Column(name = "OTHER_HELPS")
	public String getOtherHelps() {
		return this.otherHelps;
	}

	public void setOtherHelps(String otherHelps) {
		this.otherHelps = otherHelps;
	}

	@Column(name = "GREAT_OPERATION", length = 65535)
	public String getGreatOperation() {
		return this.greatOperation;
	}

	public void setGreatOperation(String greatOperation) {
		this.greatOperation = greatOperation;
	}

	@Column(name = "COUNTRY_CODE", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "COUNTRY_CODE2", length = 10)
	public String getCountryCode2() {
		return this.countryCode2;
	}

	public void setCountryCode2(String countryCode2) {
		this.countryCode2 = countryCode2;
	}

	@Column(name = "IS_READ", nullable = false)
	public Boolean getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

}
