package tw.com.mitac.thp.bean;
// Generated 2016/5/19 �U�� 04:43:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MtsDoctorItem generated by hbm2java
 */
@Entity
@Table(name = "mts_doctor_item", catalog = "thp")
public class MtsDoctorItem implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private String parentSysid;
	private String doctorIntroduction;


	public MtsDoctorItem() {
	}

	public MtsDoctorItem(String sysid, String creationDate, String creator, String operator, String operationDate,
			String parentSysid, String doctorIntroduction) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.parentSysid = parentSysid;
		this.doctorIntroduction = doctorIntroduction;
	}

	public MtsDoctorItem(String sysid, String creationDate, String creator, String operator, String operationDate,
			String remark, String parentSysid, String doctorIntroduction) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.parentSysid = parentSysid;
		this.doctorIntroduction = doctorIntroduction;
	}

	@Id

	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DOCTOR_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "DOCTOR_INTRODUCTION", length = 30)
	public String getDoctorIntroduction() {
		return this.doctorIntroduction;
	}

	public void setDoctorIntroduction(String doctorIntroduction) {
		this.doctorIntroduction = doctorIntroduction;
	}

}
