package tw.com.mitac.thp.bean;

// Generated 2016/6/11 下午 10:48:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MtsHighlight generated by hbm2java
 */
@Entity
@Table(name = "mts_highlight", catalog = "thp")
public class MtsHighlight implements java.io.Serializable {

	private String sysid;
	private String creationDate;
	private String creator;
	private String operator;
	private String operationDate;
	private String remark;
	private Integer dataOrder;
	private Boolean isEnabled;
	private String name;
	private String vendorSysid;
	private String highlightSummary;
	private String highlightSummaryImg;
	private String highlightProfileFull;
	private String highlightText2;
	private java.util.Set<MtsInfoLink> detailSet;
	private java.util.Set<MtsAdsC> detailSet2;

	public MtsHighlight() {
	}

	public MtsHighlight(String sysid, String creationDate, String creator, String operator, String operationDate,
			Integer dataOrder, Boolean isEnabled, String name, String vendorSysid) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.name = name;
		this.vendorSysid = vendorSysid;
	}

	public MtsHighlight(String sysid, String creationDate, String creator, String operator, String operationDate,
			String remark, Integer dataOrder, Boolean isEnabled, String name, String vendorSysid,
			String highlightSummary, String highlightSummaryImg, String highlightProfileFull, String highlightText2) {
		this.sysid = sysid;
		this.creationDate = creationDate;
		this.creator = creator;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.dataOrder = dataOrder;
		this.isEnabled = isEnabled;
		this.name = name;
		this.vendorSysid = vendorSysid;
		this.highlightSummary = highlightSummary;
		this.highlightSummaryImg = highlightSummaryImg;
		this.highlightProfileFull = highlightProfileFull;
		this.highlightText2 = highlightText2;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "IS_ENABLED", nullable = false)
	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "HIGHLIGHT_NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "HIGHLIGHT_SUMMARY")
	public String getHighlightSummary() {
		return this.highlightSummary;
	}

	public void setHighlightSummary(String highlightSummary) {
		this.highlightSummary = highlightSummary;
	}

	@Column(name = "HIGHLIGHT_SUMMARY_IMG", nullable = false)
	public String getHighlightSummaryImg() {
		return this.highlightSummaryImg;
	}

	public void setHighlightSummaryImg(String highlightSummaryImg) {
		this.highlightSummaryImg = highlightSummaryImg;
	}

	@Column(name = "HIGHLIGHT_PROFILE_FULL", length = 65535)
	public String getHighlightProfileFull() {
		return this.highlightProfileFull;
	}

	public void setHighlightProfileFull(String highlightProfileFull) {
		this.highlightProfileFull = highlightProfileFull;
	}

	@Column(name = "HIGHLIGHT_TEXT_2", length = 65535)
	public String getHighlightText2() {
		return this.highlightText2;
	}

	public void setHighlightText2(String highlightText2) {
		this.highlightText2 = highlightText2;
	}

	public java.util.Set<MtsInfoLink> getDetailSet() {
		return detailSet;
	}
	
	public void setDetailSet(java.util.Set<MtsInfoLink> detailSet) {
		this.detailSet = detailSet;
	}
	
	
	public java.util.Set<MtsAdsC> getDetailSet2() {
		return detailSet2;
	}

	public void setDetailSet2(java.util.Set<MtsAdsC> detailSet2) {
		this.detailSet2 = detailSet2;
	}

	
}
