package tw.com.mitac.thp.bean;

// Generated 2016/3/15 下午 01:30:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MtsOrdersFeedback generated by hbm2java
 */
@Entity
@Table(name = "mts_orders_feedback", catalog = "thp")
public class MtsOrdersFeedback implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String parentSysid;
	private String sequenceNo;
	private String feedbackDetail;
	private String memberSysid;
	private String sourceNo;
	private String sourceType;

	public MtsOrdersFeedback() {
	}

	public MtsOrdersFeedback(String sysid, String creator, String creationDate, String operator, String operationDate,
			String sequenceNo, String feedbackDetail, String sourceType) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.sequenceNo = sequenceNo;
		this.feedbackDetail = feedbackDetail;
		this.sourceType = sourceType;
	}

	public MtsOrdersFeedback(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String parentSysid, String sequenceNo, String feedbackDetail, String memberSysid,
			String sourceNo, String sourceType) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.parentSysid = parentSysid;
		this.sequenceNo = sequenceNo;
		this.feedbackDetail = feedbackDetail;
		this.memberSysid = memberSysid;
		this.sourceNo = sourceNo;
		this.sourceType = sourceType;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ORDERS_SYSID", length = 45)
	public String getParentSysid() {
		return this.parentSysid;
	}

	public void setParentSysid(String parentSysid) {
		this.parentSysid = parentSysid;
	}

	@Column(name = "SEQUENCE_NO", nullable = false, length = 10)
	public String getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(String sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Column(name = "FEEDBACK_DETAIL", nullable = false, length = 65535)
	public String getFeedbackDetail() {
		return this.feedbackDetail;
	}

	public void setFeedbackDetail(String feedbackDetail) {
		this.feedbackDetail = feedbackDetail;
	}

	@Column(name = "MEMBER_SYSID", length = 45)
	public String getMemberSysid() {
		return this.memberSysid;
	}

	public void setMemberSysid(String memberSysid) {
		this.memberSysid = memberSysid;
	}

	@Column(name = "SOURCE_NO", length = 10)
	public String getSourceNo() {
		return this.sourceNo;
	}

	public void setSourceNo(String sourceNo) {
		this.sourceNo = sourceNo;
	}

	@Column(name = "SOURCE_TYPE", nullable = false, length = 10)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

}
