package tw.com.mitac.thp.bean;

// Generated 2016/1/27 下午 05:38:37 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MtsOrders generated by hbm2java
 */
@Entity
@Table(name = "mts_orders", catalog = "thp")
public class MtsOrders implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String billno;
	private String vendorSysid;
	private String memberSysid;
	private Date issueDate;
	private String ordersDetail;
	private String ordersType;
	private BigDecimal transactionAmount;
	private String billStatus;
	private String ordersNote;
	private Boolean isOrdersToVendor;
	private Set<MtsOrdersFeedback> detailSet;
	private Set<MtsOrdersProducts> detailSet2;
	private Set<MtsOrdersItems> detailSet3;

	public Set<MtsOrdersFeedback> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(Set<MtsOrdersFeedback> detailSet) {
		this.detailSet = detailSet;
	}

	public Set<MtsOrdersProducts> getDetailSet2() {
		return detailSet2;
	}

	public void setDetailSet2(Set<MtsOrdersProducts> detailSet2) {
		this.detailSet2 = detailSet2;
	}

	public Set<MtsOrdersItems> getDetailSet3() {
		return detailSet3;
	}

	public void setDetailSet3(Set<MtsOrdersItems> detailSet3) {
		this.detailSet3 = detailSet3;
	}

	public MtsOrders() {
	}

	public MtsOrders(String sysid, String creator, String creationDate, String operator, String operationDate,
			String billno, String vendorSysid, String memberSysid, BigDecimal transactionAmount,
			Boolean isOrdersToVendor) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.billno = billno;
		this.vendorSysid = vendorSysid;
		this.memberSysid = memberSysid;
		this.transactionAmount = transactionAmount;
		this.isOrdersToVendor = isOrdersToVendor;
	}

	public MtsOrders(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, String billno, String vendorSysid, String memberSysid, Date issueDate, String ordersDetail,
			String ordersType, BigDecimal transactionAmount, String billStatus, String ordersNote,
			Boolean isOrdersToVendor) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.billno = billno;
		this.vendorSysid = vendorSysid;
		this.memberSysid = memberSysid;
		this.issueDate = issueDate;
		this.ordersDetail = ordersDetail;
		this.ordersType = ordersType;
		this.transactionAmount = transactionAmount;
		this.billStatus = billStatus;
		this.ordersNote = ordersNote;
		this.isOrdersToVendor = isOrdersToVendor;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ODNO", nullable = false, length = 45)
	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	@Column(name = "VENDOR_SYSID", nullable = false, length = 45)
	public String getVendorSysid() {
		return this.vendorSysid;
	}

	public void setVendorSysid(String vendorSysid) {
		this.vendorSysid = vendorSysid;
	}

	@Column(name = "MEMBER_SYSID", nullable = false, length = 45)
	public String getMemberSysid() {
		return this.memberSysid;
	}

	public void setMemberSysid(String memberSysid) {
		this.memberSysid = memberSysid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_DATE", length = 10)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "ORDERS_DETAIL", length = 65535)
	public String getOrdersDetail() {
		return this.ordersDetail;
	}

	public void setOrdersDetail(String ordersDetail) {
		this.ordersDetail = ordersDetail;
	}

	@Column(name = "ORDERS_TYPE", length = 45)
	public String getOrdersType() {
		return this.ordersType;
	}

	public void setOrdersType(String ordersType) {
		this.ordersType = ordersType;
	}

	@Column(name = "TRANSACTION_AMOUNT", nullable = false, precision = 21, scale = 8)
	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	@Column(name = "ORDERS_PAY_STATUS", length = 10)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "ORDERS_NOTE", length = 65535)
	public String getOrdersNote() {
		return this.ordersNote;
	}

	public void setOrdersNote(String ordersNote) {
		this.ordersNote = ordersNote;
	}

	@Column(name = "IS_ORDERS_TO_VENDOR", nullable = false)
	public Boolean getIsOrdersToVendor() {
		return this.isOrdersToVendor;
	}

	public void setIsOrdersToVendor(Boolean isOrdersToVendor) {
		this.isOrdersToVendor = isOrdersToVendor;
	}

}
