package tw.com.mitac.thp.bean;

// Generated 2016/5/9 下午 03:12:01 by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MtsRecommand generated by hbm2java
 */
@Entity
@Table(name = "mts_recommand", catalog = "thp")
public class MtsRecommand implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String recommandTitle;
	private String recommandType;
	private Integer dataOrder;
	private String remark;
	private Set<MtsRecommandItem> detailSet;

	public Set<MtsRecommandItem> getDetailSet() {
		return detailSet;
	}

	public void setDetailSet(Set<MtsRecommandItem> detailSet) {
		this.detailSet = detailSet;
	}

	public MtsRecommand() {
	}

	public MtsRecommand(String sysid, String creator, String creationDate, String operator, String operationDate,
			String recommandType, Integer dataOrder, String remark) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.recommandType = recommandType;
		this.dataOrder = dataOrder;
		this.remark = remark;
	}

	public MtsRecommand(String sysid, String creator, String creationDate, String operator, String operationDate,
			String recommandTitle, String recommandType, Integer dataOrder, String remark) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.recommandTitle = recommandTitle;
		this.recommandType = recommandType;
		this.dataOrder = dataOrder;
		this.remark = remark;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "RECOMMAND_TITLE")
	public String getRecommandTitle() {
		return this.recommandTitle;
	}

	public void setRecommandTitle(String recommandTitle) {
		this.recommandTitle = recommandTitle;
	}

	@Column(name = "RECOMMAND_TYPE", nullable = false, length = 1)
	public String getRecommandType() {
		return this.recommandType;
	}

	public void setRecommandType(String recommandType) {
		this.recommandType = recommandType;
	}

	@Column(name = "DATA_ORDER", nullable = false)
	public Integer getDataOrder() {
		return this.dataOrder;
	}

	public void setDataOrder(Integer dataOrder) {
		this.dataOrder = dataOrder;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}