package tw.com.mitac.thp.bean;

// Generated 2014/4/29 �U�� 03:37:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysBillnomanagement generated by hbm2java
 */
@Entity
@Table(name = "sys_billnomanagement")
public class SysBillnomanagement implements java.io.Serializable {

	private String sysid;
	private String operator;
	private String operationDate;
	private String creator;
	private String creationDate;
	private String remark;
	private String dataId;
	private String billname;
	private String classname;
	private String property;
	private String headword;
	private Long headlength;
	private Long totallength;

	public SysBillnomanagement() {
	}

	public SysBillnomanagement(String sysid, String operator, String operationDate, String creator,
			String creationDate, String dataId, String billname, String classname, String property, String headword,
			Long headlength, Long totallength) {
		this.sysid = sysid;
		this.operator = operator;
		this.operationDate = operationDate;
		this.creator = creator;
		this.creationDate = creationDate;
		this.dataId = dataId;
		this.billname = billname;
		this.classname = classname;
		this.property = property;
		this.headword = headword;
		this.headlength = headlength;
		this.totallength = totallength;
	}

	public SysBillnomanagement(String sysid, String operator, String operationDate, String creator,
			String creationDate, String remark, String dataId, String billname, String classname, String property,
			String headword, Long headlength, Long totallength) {
		this.sysid = sysid;
		this.operator = operator;
		this.operationDate = operationDate;
		this.creator = creator;
		this.creationDate = creationDate;
		this.remark = remark;
		this.dataId = dataId;
		this.billname = billname;
		this.classname = classname;
		this.property = property;
		this.headword = headword;
		this.headlength = headlength;
		this.totallength = totallength;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "BILLNOMANAGEMENTID", nullable = false)
	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	@Column(name = "BILLNAME", nullable = false)
	public String getBillname() {
		return this.billname;
	}

	public void setBillname(String billname) {
		this.billname = billname;
	}

	@Column(name = "CLASSNAME", nullable = false)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "PROPERTY", nullable = false)
	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	@Column(name = "HEADWORD", nullable = false)
	public String getHeadword() {
		return this.headword;
	}

	public void setHeadword(String headword) {
		this.headword = headword;
	}

	@Column(name = "HEADLENGTH", nullable = false, precision = 13, scale = 0)
	public Long getHeadlength() {
		return this.headlength;
	}

	public void setHeadlength(Long headlength) {
		this.headlength = headlength;
	}

	@Column(name = "TOTALLENGTH", nullable = false, precision = 13, scale = 0)
	public Long getTotallength() {
		return this.totallength;
	}

	public void setTotallength(Long totallength) {
		this.totallength = totallength;
	}

}
