package tw.com.mitac.thp.bean;

// Generated 2016/1/25 上午 11:25:37 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysBillHistory generated by hbm2java
 */
@Entity
@Table(name = "sys_bill_history", catalog = "thp")
public class SysBillHistory implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private Date actionTime;
	private String sourceSysid;
	private String sourceNo;
	private String billStatus;

	public SysBillHistory() {
	}

	public SysBillHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			Date actionTime, String sourceSysid, String sourceNo, String billStatus) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.actionTime = actionTime;
		this.sourceSysid = sourceSysid;
		this.sourceNo = sourceNo;
		this.billStatus = billStatus;
	}

	public SysBillHistory(String sysid, String creator, String creationDate, String operator, String operationDate,
			String remark, Date actionTime, String sourceSysid, String sourceNo, String billStatus) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.actionTime = actionTime;
		this.sourceSysid = sourceSysid;
		this.sourceNo = sourceNo;
		this.billStatus = billStatus;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTION_TIME", nullable = false, length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "SOURCE_SYSID", nullable = false, length = 45)
	public String getSourceSysid() {
		return this.sourceSysid;
	}

	public void setSourceSysid(String sourceSysid) {
		this.sourceSysid = sourceSysid;
	}

	@Column(name = "SOURCE_NO", nullable = false, length = 10)
	public String getSourceNo() {
		return this.sourceNo;
	}

	public void setSourceNo(String sourceNo) {
		this.sourceNo = sourceNo;
	}

	@Column(name = "BILL_STATUS", nullable = false, length = 10)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

}
