package tw.com.mitac.thp.bean;

// Generated 2014/4/19 �W�� 11:38:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysConstant generated by hbm2java
 */
@Entity
@Table(name = "sys_constant")
public class SysConstant implements java.io.Serializable {

	private String sysid;
	private String operator;
	private String operationDate;
	private String creator;
	private String creationDate;
	private String remark;
	private String constantId;
	private String constantName;
	private String constantType;
	private String constantOption;
	private String defaultOption;
	private String tableName;

	public SysConstant() {
	}

	public SysConstant(String sysid, String operator, String operationDate, String creator, String creationDate,
			String constantId, String constantName, String constantOption, String tableName) {
		this.sysid = sysid;
		this.operator = operator;
		this.operationDate = operationDate;
		this.creator = creator;
		this.creationDate = creationDate;
		this.constantId = constantId;
		this.constantName = constantName;
		this.constantOption = constantOption;
		this.tableName = tableName;
	}

	public SysConstant(String sysid, String operator, String operationDate, String creator, String creationDate,
			String remark, String constantId, String constantName, String constantType, String constantOption,
			String defaultOption, String tableName) {
		this.sysid = sysid;
		this.operator = operator;
		this.operationDate = operationDate;
		this.creator = creator;
		this.creationDate = creationDate;
		this.remark = remark;
		this.constantId = constantId;
		this.constantName = constantName;
		this.constantType = constantType;
		this.constantOption = constantOption;
		this.defaultOption = defaultOption;
		this.tableName = tableName;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CONSTANT_ID", nullable = false)
	public String getConstantId() {
		return this.constantId;
	}

	public void setConstantId(String constantId) {
		this.constantId = constantId;
	}

	@Column(name = "CONSTANT_NAME", nullable = false)
	public String getConstantName() {
		return this.constantName;
	}

	public void setConstantName(String constantName) {
		this.constantName = constantName;
	}

	@Column(name = "CONSTANT_TYPE")
	public String getConstantType() {
		return this.constantType;
	}

	public void setConstantType(String constantType) {
		this.constantType = constantType;
	}

	@Column(name = "CONSTANT_OPTION", nullable = false, length = 65535)
	public String getConstantOption() {
		return this.constantOption;
	}

	public void setConstantOption(String constantOption) {
		this.constantOption = constantOption;
	}

	@Column(name = "DEFAULT_OPTION")
	public String getDefaultOption() {
		return this.defaultOption;
	}

	public void setDefaultOption(String defaultOption) {
		this.defaultOption = defaultOption;
	}

	@Column(name = "TABLE_NAME", nullable = false, length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

}
