package tw.com.mitac.thp.bean;

// Generated 2015/8/31 上午 09:59:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysJobScheduleSetting generated by hbm2java
 */
@Entity
@Table(name = "sys_job_schedule_setting")
public class SysJobScheduleSetting implements java.io.Serializable {

	private String sysid;
	private String operator;
	private String operationDate;
	private String creator;
	private String creationDate;
	private String remark;
	private String className;
	private String groupName;
	private String triggerName;
	private String jobName;
	private String description;
	private String cronTime;
	private String second;
	private String minute;
	private String hour;
	private String day;
	private String month;
	private String week;
	private String year;
	private String cronexpression;
	private Boolean jobenable;
	private Boolean isOneTimeExcute;
	private String startOnRemoteHost;

	public SysJobScheduleSetting() {
	}

	public SysJobScheduleSetting(String sysid, String className, String groupName, String jobName, String description,
			Boolean jobenable, Boolean isOneTimeExcute, String startOnRemoteHost) {
		this.sysid = sysid;
		this.className = className;
		this.groupName = groupName;
		this.jobName = jobName;
		this.description = description;
		this.jobenable = jobenable;
		this.isOneTimeExcute = isOneTimeExcute;
		this.startOnRemoteHost = startOnRemoteHost;
	}

	public SysJobScheduleSetting(String sysid, String operator, String operationDate, String creator,
			String creationDate, String remark, String className, String groupName, String triggerName, String jobName,
			String description, String cronTime, String second, String minute, String hour, String day, String month,
			String week, String year, String cronexpression, Boolean jobenable, Boolean isOneTimeExcute,
			String startOnRemoteHost) {
		this.sysid = sysid;
		this.operator = operator;
		this.operationDate = operationDate;
		this.creator = creator;
		this.creationDate = creationDate;
		this.remark = remark;
		this.className = className;
		this.groupName = groupName;
		this.triggerName = triggerName;
		this.jobName = jobName;
		this.description = description;
		this.cronTime = cronTime;
		this.second = second;
		this.minute = minute;
		this.hour = hour;
		this.day = day;
		this.month = month;
		this.week = week;
		this.year = year;
		this.cronexpression = cronexpression;
		this.jobenable = jobenable;
		this.isOneTimeExcute = isOneTimeExcute;
		this.startOnRemoteHost = startOnRemoteHost;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "OPERATOR")
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE")
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "CREATOR")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE")
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CLASS_NAME", nullable = false)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "GROUP_NAME", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "TRIGGER_NAME")
	public String getTriggerName() {
		return this.triggerName;
	}

	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	@Column(name = "JOB_NAME", nullable = false)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "DESCRIPTION", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CRON_TIME", length = 50)
	public String getCronTime() {
		return this.cronTime;
	}

	public void setCronTime(String cronTime) {
		this.cronTime = cronTime;
	}

	@Column(name = "SECOND", length = 5)
	public String getSecond() {
		return this.second;
	}

	public void setSecond(String second) {
		this.second = second;
	}

	@Column(name = "MINUTE", length = 5)
	public String getMinute() {
		return this.minute;
	}

	public void setMinute(String minute) {
		this.minute = minute;
	}

	@Column(name = "HOUR", length = 5)
	public String getHour() {
		return this.hour;
	}

	public void setHour(String hour) {
		this.hour = hour;
	}

	@Column(name = "DAY", length = 5)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "MONTH", length = 5)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "WEEK", length = 5)
	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	@Column(name = "YEAR", length = 10)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "CRONEXPRESSION", length = 50)
	public String getCronexpression() {
		return this.cronexpression;
	}

	public void setCronexpression(String cronexpression) {
		this.cronexpression = cronexpression;
	}

	@Column(name = "JOBENABLE", nullable = false)
	public Boolean getJobenable() {
		return this.jobenable;
	}

	public void setJobenable(Boolean jobenable) {
		this.jobenable = jobenable;
	}

	@Column(name = "IS_ONE_TIME_EXCUTE", nullable = false)
	public Boolean getIsOneTimeExcute() {
		return this.isOneTimeExcute;
	}

	public void setIsOneTimeExcute(Boolean isOneTimeExcute) {
		this.isOneTimeExcute = isOneTimeExcute;
	}

	@Column(name = "START_ON_REMOTE_HOST", nullable = false)
	public String getStartOnRemoteHost() {
		return this.startOnRemoteHost;
	}

	public void setStartOnRemoteHost(String startOnRemoteHost) {
		this.startOnRemoteHost = startOnRemoteHost;
	}

}
