package tw.com.mitac.thp.bean;

// Generated 2016/5/9 上午 10:23:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysMultiLanguage_zh_TW generated by hbm2java
 */
@Entity
@Table(name = "sys_multi_language_zh_tw", catalog = "thp")
public class SysMultiLanguage_zh_TW implements java.io.Serializable {

	private String sysid;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private String remark;
	private String sourceSysid;
	private String sourceTable;
	private String sourceColumn;
	private String columnDatatype;
	private Long columnLength;
	private String columnValueString;
	private String columnValueText;

	public SysMultiLanguage_zh_TW() {
	}

	public SysMultiLanguage_zh_TW(String sysid, String creator, String creationDate, String operator,
			String operationDate, String sourceSysid, String sourceTable, String sourceColumn, String columnDatatype,
			Long columnLength) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.sourceSysid = sourceSysid;
		this.sourceTable = sourceTable;
		this.sourceColumn = sourceColumn;
		this.columnDatatype = columnDatatype;
		this.columnLength = columnLength;
	}

	public SysMultiLanguage_zh_TW(String sysid, String creator, String creationDate, String operator,
			String operationDate, String remark, String sourceSysid, String sourceTable, String sourceColumn,
			String columnDatatype, Long columnLength, String columnValueString, String columnValueText) {
		this.sysid = sysid;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.remark = remark;
		this.sourceSysid = sourceSysid;
		this.sourceTable = sourceTable;
		this.sourceColumn = sourceColumn;
		this.columnDatatype = columnDatatype;
		this.columnLength = columnLength;
		this.columnValueString = columnValueString;
		this.columnValueText = columnValueText;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SOURCE_SYSID", nullable = false, length = 45)
	public String getSourceSysid() {
		return this.sourceSysid;
	}

	public void setSourceSysid(String sourceSysid) {
		this.sourceSysid = sourceSysid;
	}

	@Column(name = "SOURCE_TABLE", nullable = false, length = 50)
	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "SOURCE_COLUMN", nullable = false, length = 50)
	public String getSourceColumn() {
		return this.sourceColumn;
	}

	public void setSourceColumn(String sourceColumn) {
		this.sourceColumn = sourceColumn;
	}

	@Column(name = "COLUMN_DATATYPE", nullable = false, length = 50)
	public String getColumnDatatype() {
		return this.columnDatatype;
	}

	public void setColumnDatatype(String columnDatatype) {
		this.columnDatatype = columnDatatype;
	}

	@Column(name = "COLUMN_LENGTH", nullable = false, precision = 13, scale = 0)
	public Long getColumnLength() {
		return this.columnLength;
	}

	public void setColumnLength(Long columnLength) {
		this.columnLength = columnLength;
	}

	@Column(name = "COLUMN_VALUE_STRING")
	public String getColumnValueString() {
		return this.columnValueString;
	}

	public void setColumnValueString(String columnValueString) {
		this.columnValueString = columnValueString;
	}

	@Column(name = "COLUMN_VALUE_TEXT", length = 65535)
	public String getColumnValueText() {
		return this.columnValueText;
	}

	public void setColumnValueText(String columnValueText) {
		this.columnValueText = columnValueText;
	}

}
