package tw.com.mitac.miaa.bean;

// Generated 2015/5/11 上午 11:27:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miaa09CustomFunction generated by hbm2java
 */
@Entity
@Table(name = "miaa09_custom_file")
public class Miaa09CustomFile implements java.io.Serializable {

	private String sysid;
	private String fileSysid;
	private Integer customId;
	private String uid;

	public Miaa09CustomFile() {
	}

	public Miaa09CustomFile(String sysid, String fileSysid, Integer customId, String uid) {
		this.sysid = sysid;
		this.fileSysid = fileSysid;
		this.customId = customId;
		this.uid = uid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "FILE_SYSID", nullable = false, length = 45)
	public String getFileSysid() {
		return this.fileSysid;
	}

	public void setFileSysid(String fileSysid) {
		this.fileSysid = fileSysid;
	}

	@Column(name = "CUSTOM_ID", nullable = false)
	public Integer getCustomId() {
		return this.customId;
	}

	public void setCustomId(Integer customId) {
		this.customId = customId;
	}

	@Column(name = "UID", nullable = false)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

}
