package tw.com.mitac.miaa.bean;

// Generated 2015/4/23 下午 05:40:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miaa02File generated by hbm2java
 */
@Entity
@Table(name = "miaa02_file")
public class Miaa02File implements java.io.Serializable {

	private String sysid;
	private String fileId;
	private String fileName;
	private String initUrl;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private Boolean isEnable;

	public Miaa02File() {
	}

	public Miaa02File(String sysid, String fileId, String fileName, String initUrl, String creator,
			String creationDate, String operator, String operationDate, Boolean isEnable) {
		this.sysid = sysid;
		this.fileId = fileId;
		this.fileName = fileName;
		this.initUrl = initUrl;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.isEnable = isEnable;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "FILE_ID", nullable = false)
	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	@Column(name = "FILE_NAME", nullable = false)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "INIT_URL", nullable = false)
	public String getInitUrl() {
		return this.initUrl;
	}

	public void setInitUrl(String initUrl) {
		this.initUrl = initUrl;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "IS_ENABLE", nullable = false)
	public Boolean getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

}
