package tw.com.mitac.miaa.bean;

// Generated 2015/4/10 上午 10:56:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miaa04Role generated by hbm2java
 */
@Entity
@Table(name = "miaa04_role")
public class Miaa04Role implements java.io.Serializable {

	private String sysid;
	private String roleId;
	private String roleName;
	private String roleDesc;
	private String creator;
	private String creationDate;
	private String operator;
	private String operationDate;
	private Boolean isEnable;

	public Miaa04Role() {
	}

	public Miaa04Role(String sysid, String roleId, String roleName, String creator, String creationDate,
			String operator, String operationDate, Boolean isEnable) {
		this.sysid = sysid;
		this.roleId = roleId;
		this.roleName = roleName;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.isEnable = isEnable;
	}

	public Miaa04Role(String sysid, String roleId, String roleName, String roleDesc, String creator,
			String creationDate, String operator, String operationDate, Boolean isEnable) {
		this.sysid = sysid;
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.creator = creator;
		this.creationDate = creationDate;
		this.operator = operator;
		this.operationDate = operationDate;
		this.isEnable = isEnable;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", nullable = false)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_DESC")
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "CREATOR", nullable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "CREATION_DATE", nullable = false)
	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "OPERATOR", nullable = false)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATION_DATE", nullable = false)
	public String getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(String operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "IS_ENABLE", nullable = false)
	public Boolean getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

}
