package tw.com.mitac.miaa.bean;

// Generated 2015/5/11 上午 11:27:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miaa08RoleUid generated by hbm2java
 */
@Entity
@Table(name = "miaa08_role_uid")
public class Miaa08RoleUid implements java.io.Serializable {

	private String sysid;
	private String roleSysid;
	private String uid;

	public Miaa08RoleUid() {
	}

	public Miaa08RoleUid(String sysid, String roleSysid, String uid) {
		this.sysid = sysid;
		this.roleSysid = roleSysid;
		this.uid = uid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "ROLE_SYSID", nullable = false, length = 45)
	public String getRoleSysid() {
		return this.roleSysid;
	}

	public void setRoleSysid(String roleSysid) {
		this.roleSysid = roleSysid;
	}

	@Column(name = "UID", nullable = false)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

}
