package tw.com.mitac.miaa.bean;

// Generated 2015/4/10 上午 10:56:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Miaa05TagFile generated by hbm2java
 */
@Entity
@Table(name = "miaa05_tag_file")
public class Miaa05TagFile implements java.io.Serializable {

	private String sysid;
	private String tagSysid;
	private String fileSysid;

	public Miaa05TagFile() {
	}

	public Miaa05TagFile(String sysid, String tagSysid, String fileSysid) {
		this.sysid = sysid;
		this.tagSysid = tagSysid;
		this.fileSysid = fileSysid;
	}

	@Id
	@Column(name = "SYSID", unique = true, nullable = false, length = 45)
	public String getSysid() {
		return this.sysid;
	}

	public void setSysid(String sysid) {
		this.sysid = sysid;
	}

	@Column(name = "TAG_SYSID", nullable = false, length = 45)
	public String getTagSysid() {
		return this.tagSysid;
	}

	public void setTagSysid(String tagSysid) {
		this.tagSysid = tagSysid;
	}

	@Column(name = "FILE_SYSID", nullable = false, length = 45)
	public String getFileSysid() {
		return this.fileSysid;
	}

	public void setFileSysid(String fileSysid) {
		this.fileSysid = fileSysid;
	}

}
