package tw.com.mitac.thp.action;

// Generated Tue May 10 20:26:59 CST 2016 by GenCode.java

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.BhsMarquee;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsMember;
import tw.com.mitac.thp.bean.CpsVendor;

/**
 * BhsMarqueeAction generated by GenCode.java
 */
public class BhsMarqueeAction extends BasisCrudAction<BhsMarquee> {

	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule(SOURCE_ID, "BHS"));
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule(SOURCE_ID, getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String edit() {
		// 預設值
		if (StringUtils.isBlank(bean.getSysid())) {
			CpsMember user = getUserAccount();
			if (CpsEntity.class.getSimpleName().equals(user.getSourceType())) {
				bean.setSourceId("BHS");
			} else if (CpsVendor.class.getSimpleName().equals(user.getSourceType())) {
				bean.setSourceId(user.getSourceSysid());
			}
		}
		String result = super.edit();
		return result;
	}

}