package tw.com.mitac.thp.action;

// Generated Thu May 12 14:38:56 CST 2016 by GenCode.java

import java.util.List;

import org.apache.commons.beanutils.ConstructorUtils;
import org.apache.commons.beanutils.PropertyUtils;
import org.apache.commons.lang3.StringUtils;
import org.codehaus.groovy.control.CompilationUnit.SourceUnitOperation;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.BhsMarquee;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsMember;
import tw.com.mitac.thp.bean.CpsVendor;

/**
 * BhsMarquee2Action generated by GenCode.java
 */
public class BhsMarquee2Action extends BasisCrudAction<BhsMarquee> {

	// 此功能館主可看全部單,關閉排序功能
	@Override
	public Boolean getJqgridDefaultSoab() {
		if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType()))
			return true;
		return false;
	}
	
	@Override
	public String getJqgridDefaultSidx() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType()))
			return SOURCE_ID;
		return super.getJqgridDefaultSidx();
	}
	
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule(SOURCE_ID, "BHS"));
			} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule(SOURCE_ID, getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	protected Object[] jqgridList(Class<?> clazz, QueryGroup queryGroup, QueryOrder[] orders, Integer from,
			Integer length) {
		Object[] oldArr = super.jqgridList(clazz, queryGroup, orders, from, length);
		List<BhsMarquee> list = (List<BhsMarquee>) oldArr[1];
		for (BhsMarquee bean : list) {
			String sourceId = bean.getSourceId();
			if (!"BHS".equals(sourceId)) {
				CpsVendor source = createDataTable(CpsVendor.class).get(sourceId);
				if (source != null)
					bean.setSourceId(source.getName());
			}
		}
		Object[] newArr = new Object[] { oldArr[0], list };
		return newArr;
	}

	@Override
	public String edit() {
		// 預設值
		if (StringUtils.isBlank(bean.getSysid())) {
			CpsMember user = getUserAccount();
			if (CpsEntity.class.getSimpleName().equals(user.getSourceType())) {
				bean.setSourceId("BHS");
			} else if (CpsVendor.class.getSimpleName().equals(user.getSourceType())) {
				bean.setSourceId(user.getSourceSysid());
			}
		}
		String result = super.edit();
		return result;
	}

}