package tw.com.mitac.thp.action;

// Generated Tue May 10 20:26:59 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.BhsProductsCategory;

/**
 * BhsProductsCategoryAction generated by GenCode.java
 */
public class BhsProductsCategoryAction extends BasisCrudAction<BhsProductsCategory> {
}