package tw.com.mitac.thp.action;

import java.util.Calendar;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;
// Generated Sat Jun 04 14:36:49 CST 2016 by GenCode.java
import tw.com.mitac.thp.bean.CpsExhibitionList;

/**
 * CpsExhibitionListAction generated by GenCode.java
 */
public class CpsExhibitionListAction extends BasisCrudAction<CpsExhibitionList> {

	@Override
	public String[] getImgCols() {
		return new String[] { "exhibitionBanner", "exhibitionSummaryImg" };
	}

	@Override
	public String edit() {
		// TODO Auto-generated method stub
		String result = super.edit();
		// 判斷creat是否有值 沒有值的話給預設值
		if (StringUtils.isBlank(bean.getCreator())) {

			// exhibitionEndDate
			// 1.今天變成calender 2.加一個月 3.變回date
			Calendar now = Calendar.getInstance();
			// now.set(2016, 6, 4);
			// systemDate是現在日期 systemDatetime是現在日期加時間
			now.setTime(systemDate);
			now.add(Calendar.MONTH, 1);

			Date dat = now.getTime();

			bean.setExhibitionEndDate(dat);

		}

		return result;
	}
}