package tw.com.mitac.thp.action;

// Generated Sun Apr 10 13:06:46 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.CpsEmailHistory;

/**
 * CpsEmailHistoryAction generated by GenCode.java
 */
public class CpsEmailHistoryAction extends BasisCrudAction<CpsEmailHistory> {
}