package tw.com.mitac.thp.action;

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.thp.bean.CpsEntity;

// Generated Mon May 30 10:00:40 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.CpsMarquee;
import tw.com.mitac.thp.bean.CpsMember;
import tw.com.mitac.thp.bean.CpsVendor;

/**
 * CpsMarqueeAction generated by GenCode.java
 */
public class CpsMarqueeAction extends BasisCrudAction<CpsMarquee> {
	
	
	
	@Override
	public String edit() {
		// 預設值
		if (StringUtils.isBlank(bean.getEntitySysid())) {
			CpsMember user = getUserAccount();
			if (CpsEntity.class.getSimpleName().equals(user.getSourceType())) {
				bean.setEntitySysid(user.getSourceSysid());
			} 
		}
		String result = super.edit();
		return result;
	}
	
	
	
	
	
}