package tw.com.mitac.thp.action;

// Generated Tue Mar 15 14:23:28 CST 2016 by GenCode.java

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;

/**
 * CpsQaAction generated by GenCode.java
 */
public class CpsQaForMtsAction extends CpsQaAction {
//	@Override
//	protected QueryGroup getQueryRestrict() {
//		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
//			return new QueryGroup(new QueryRule("qaDepartment", "MTS"));
//		} else {
//			return new QueryGroup(new QueryRule(PK, "x"));
//		}
//	}
}