package tw.com.mitac.thp.action;

import java.util.List;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.BhsHighlight;
import tw.com.mitac.thp.bean.BhsProducts;
import tw.com.mitac.thp.bean.BhsTechnology;
import tw.com.mitac.thp.bean.BhsVendorProfile;
import tw.com.mitac.thp.bean.CpsEntity;

// Generated Sat Jun 04 19:51:22 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.CpsSiteMember;
import tw.com.mitac.thp.bean.CpsVendor;

/**
 * CpsSiteMember2BhsAction generated by GenCode.java
 */
public class CpsSiteMember2BhsAction extends CpsSiteMember2BasisAction<CpsSiteMember> {

	@Override
	protected String getEntityType() {
		return "BHS";
	}

	public List<BhsTechnology> getBhsTechnologyList() {
		List<BhsTechnology> bhsTechnologyList = null;
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsTechnologyList = cloudDao.queryTable(sf(), BhsTechnology.class, new QueryGroup(), new QueryOrder[0],
					null, null);

		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsTechnologyList = cloudDao.queryTable(sf(), BhsTechnology.class,
					new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0],
					null, null);

		}
		request.setAttribute("bhsTechnologyList", bhsTechnologyList);
		return bhsTechnologyList;
	}

	public List<BhsHighlight> getBhsHighlightList() {
		List<BhsHighlight> bhsHighlightList = null;
		
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsHighlightList = cloudDao.queryTable(sf(), BhsHighlight.class, new QueryGroup(), new QueryOrder[0],
					null, null);

		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsHighlightList = cloudDao.queryTable(sf(), BhsHighlight.class,
					new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0],
					null, null);

		}
		request.setAttribute("bhsHighlightList", bhsHighlightList);

		return bhsHighlightList;
	}

	public List<BhsProducts> getBhsProductsList() {
		
		List<BhsProducts> bhsProductsList =null;
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsProductsList = cloudDao.queryTable(sf(), BhsProducts.class, new QueryGroup(), new QueryOrder[0],
					null, null);

		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsProductsList = cloudDao.queryTable(sf(), BhsProducts.class,
					new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0],
					null, null);

		}
		
		request.setAttribute("bhsProductsList", bhsProductsList);

		return bhsProductsList;
	}

	
	public List<BhsVendorProfile> getBhsVendorProfileList() {
		
		List<BhsVendorProfile> bhsVendorProfileList =null;
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsVendorProfileList = cloudDao.queryTable(sf(), BhsVendorProfile.class, new QueryGroup(), new QueryOrder[0],
					null, null);

		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {

			bhsVendorProfileList = cloudDao.queryTable(sf(), BhsVendorProfile.class,
					new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0],
					null, null);

		}
		
		request.setAttribute("bhsVendorProfileList", bhsVendorProfileList);

		return bhsVendorProfileList;
	}
}