package tw.com.mitac.thp.action;

// Generated Mon Apr 25 14:31:10 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.CpsSmsMoFee;

/**
 * CpsSmsMoFeeAction generated by GenCode.java
 */
public class CpsSmsMoFeeAction extends BasisCrudAction<CpsSmsMoFee> {
}