package tw.com.mitac.thp.action;

// Generated Sat May 14 10:58:38 CST 2016 by GenCode.java

/**
 * CpsSiteMemberAction generated by GenCode.java
 */
public class CpsSiteMemberForSuccessorAction extends CpsSiteMemberAction {
}