package tw.com.mitac.thp.action;

// Generated Fri Jan 29 16:08:50 CST 2016 by mitac-tool

import tw.com.mitac.thp.bean.CpsZipcode;

/**
 * CpsZipcodeAction generated by mitac-tool
 */
public class CpsZipcodeAction extends BasisCrudAction<CpsZipcode> {
}