package tw.com.mitac.thp.action;

// Generated Tue Apr 19 11:42:51 CST 2016 by GenCode.java

import java.util.List;

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsCoreFaq;

/**
 * HpsCoreFaqAction generated by GenCode.java
 */
public class HpsCoreFaqAction extends BasisCrudAction<HpsCoreFaq> {

	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	public String edit() {
		// 預設值
		if (StringUtils.isBlank(bean.getSysid())) {
			List<CpsEntity> entitys = cloudDao.queryTable(sf(), CpsEntity.class, new QueryGroup(new QueryRule("dataId",
					"hps")), new QueryOrder[0], null, null);
			if (entitys.size() > 0)
				bean.setEntitySysid(entitys.get(0).getSysid());
		}
		String result = super.edit();
		return result;
	}

	@Override
	protected boolean executeSave() {
		if (StringUtils.isBlank(bean.getFaqAnswer())) {
			addActionError("請填寫「常見問題回覆」");
			return false;
		}
		return super.executeSave();
	}
}