package tw.com.mitac.thp.action;

// Generated Fri Apr 01 14:03:50 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.HpsCoreVendor;

/**
 * HpsCoreVendorAction generated by GenCode.java
 */
public class HpsCoreVendorAction extends BasisCrudAction<HpsCoreVendor> {
}