package tw.com.mitac.thp.action;

// Generated Wed Mar 30 11:43:31 CST 2016 by GenCode.java

import java.util.LinkedHashMap;

import tw.com.mitac.thp.bean.HpsCoreAr;
import tw.com.mitac.thp.bean.HpsCoreArAdRentDetail;
import tw.com.mitac.thp.bean.HpsCoreArContractDetail;
import tw.com.mitac.thp.bean.HpsCoreArSoDetail;

/**
 * HpsCoreArAction generated by GenCode.java
 */
public class HpsCoreArAction extends DetailController<HpsCoreAr> {
	@Override
	public LinkedHashMap<String, DetailInfo> getDetailInfoMap() {
		LinkedHashMap<String, DetailInfo> detailClassMap = super.getDetailInfoMap();
		detailClassMap.put("", new DetailInfo("", DETAIL_SET, "detail", HpsCoreArSoDetail.class));
		detailClassMap.put("2", new DetailInfo("2", DETAIL_SET2, "detail2", HpsCoreArContractDetail.class));
		detailClassMap.put("3", new DetailInfo("3", DETAIL_SET3, "detail3", HpsCoreArAdRentDetail.class));
		return detailClassMap;
	}
	
}