package tw.com.mitac.thp.action;

// Generated Wed Apr 20 17:06:12 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.HpsCoreSearchKeyword;

/**
 * HpsCoreSearchKeywordAction generated by GenCode.java
 */
public class HpsCoreSearchKeywordAction extends BasisCrudAction<HpsCoreSearchKeyword> {
}