package tw.com.mitac.thp.action;

// Generated Mon Apr 25 11:11:12 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.HpsCoreBrandTypeBrand;

/**
 * HpsCoreBrandTypeBrandAction generated by GenCode.java
 */
public class HpsCoreBrandTypeBrandAction extends BasisCrudAction<HpsCoreBrandTypeBrand> {
}