package tw.com.mitac.thp.action;

// Generated Sun Apr 17 10:42:07 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.HpsCoreFavoriteItem;

/**
 * HpsCoreFavoriteItemAction generated by GenCode.java
 */
public class HpsCoreFavoriteItemAction extends BasisCrudAction<HpsCoreFavoriteItem> {
}