package tw.com.mitac.thp.action;

// Generated Wed May 04 09:22:09 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.HpsPromoteLimit;

/**
 * HpsPromoteLimitAction generated by GenCode.java
 */
public class HpsPromoteLimitAction extends BasisCrudAction<HpsPromoteLimit> {
}