package tw.com.mitac.thp.action;

// Generated Thu Jan 14 17:00:47 CST 2016 by mitac-tool

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.thp.bean.HpsPromoteBonus;
import tw.com.mitac.thp.bean.HpsPromotionItem;
import tw.com.mitac.thp.util.ConstantUtil;

/**
 * HpsPromoteBonusAction generated by mitac-tool
 */
public class HpsPromoteBonusAction extends DetailController<HpsPromoteBonus> {
	@Override
	public LinkedHashMap<String, DetailInfo> getDetailInfoMap() {
		LinkedHashMap<String, DetailInfo> detailClassMap = super.getDetailInfoMap();
		detailClassMap.put("", new DetailInfo("", DETAIL_SET, "detail", HpsPromotionItem.class));
		return detailClassMap;
	}

//	@Override
//	public String save() {
//		String typeOfUse = bean.getTypeOfUse();
//		Set<HpsPromotionItem> detailSet = (Set<HpsPromotionItem>) sessionGet(DETAIL_SET);
//		if (ConstantUtil.TYPE_OF_USE_ALL.equals(typeOfUse)) {
//			detailSet.clear();
//		} else {
//			// TODO 還沒寫完
//			List<HpsPromotionItem> delList = new ArrayList<HpsPromotionItem>();
//			for (HpsPromotionItem hpsPromotionItem : detailSet) {
//				hpsPromotionItem.setSourceType(HpsPromoteBonus.class.getSimpleName());
//
//				String applyType = hpsPromotionItem.getApplyType();
//				String itemSysid = hpsPromotionItem.getItemSysid();
//				String itemTypeSysid = hpsPromotionItem.getItemTypeSysid();
//				if (ConstantUtil.TYPE_OF_USE_TYPE.equals(typeOfUse) && !ConstantUtil.APPLY_TYPE_TYPE.equals(applyType)) {
//					logger.warn("APPLY_TYPE_WORNG");
//					addActionError(getText("bean.applyType") + "應設定"
//							+ getText("bean.applyType." + ConstantUtil.APPLY_TYPE_TYPE));
//					delList.add(hpsPromotionItem);
//				} else if (ConstantUtil.TYPE_OF_USE_ITEM.equals(typeOfUse)
//						&& !ConstantUtil.APPLY_TYPE_ITEM.equals(applyType)) {
//					logger.warn("APPLY_TYPE_WORNG");
//					addActionError(getText("bean.applyType") + "應設定"
//							+ getText("bean.applyType." + ConstantUtil.APPLY_TYPE_ITEM));
//					delList.add(hpsPromotionItem);
//				} else if (ConstantUtil.APPLY_TYPE_ITEM.equals(applyType)) {
//					if (StringUtils.isNotBlank(itemSysid)) {
//						hpsPromotionItem.setItemTypeSysid("");
//					} else {
//						logger.warn("NEED itemSysid");
//						addActionError("應設定" + getText("bean.itemSysid"));
//						delList.add(hpsPromotionItem);
//					}
//				} else if (ConstantUtil.APPLY_TYPE_TYPE.equals(applyType)) {
//					if (StringUtils.isNotBlank(itemTypeSysid)) {
//						hpsPromotionItem.setItemSysid("");
//					} else {
//						logger.warn("NEED itemTypeSysid");
//						addActionError("應設定" + getText("bean.itemTypeSysid"));
//						delList.add(hpsPromotionItem);
//					}
//				}
//			}
//			if (delList.size() > 0)
//				return EDIT_ERROR;
//			// detailSet.removeAll(delList);
//		}
//		return super.save();
//	}
}