package tw.com.mitac.thp.action;

// Generated Thu Jan 14 17:00:47 CST 2016 by mitac-tool

import tw.com.mitac.thp.bean.HpsPromotePlus;

/**
 * HpsPromoteBonusAction generated by mitac-tool
 */
public class HpsPromotePlusAction extends BasisCrudAction<HpsPromotePlus> {
}