package tw.com.mitac.thp.action;

// Generated Thu Jan 14 17:00:47 CST 2016 by mitac-tool

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.thp.bean.HpsPromoteBonus;
import tw.com.mitac.thp.bean.HpsPromotionItem;
import tw.com.mitac.thp.util.ConstantUtil;

/**
 * HpsPromoteBonusAction generated by mitac-tool
 */
public class HpsPromoteBonus2Action extends DetailController<HpsPromoteBonus> {
	@Override
	public LinkedHashMap<String, DetailInfo> getDetailInfoMap() {
		LinkedHashMap<String, DetailInfo> detailClassMap = super.getDetailInfoMap();
		detailClassMap.put("", new DetailInfo("", DETAIL_SET, "detail", HpsPromotionItem.class));
		return detailClassMap;
	}

}