package tw.com.mitac.thp.action;

// Generated Thu Jan 14 17:00:47 CST 2016 by mitac-tool

import tw.com.mitac.thp.bean.HpsPromoteDiscount;

/**
 * HpsPromoteBonusAction generated by mitac-tool
 */
public class HpsPromoteDiscountAction extends BasisCrudAction<HpsPromoteDiscount> {
}