package tw.com.mitac.thp.action;

// Generated Thu Apr 07 13:21:28 CST 2016 by GenCode.java

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorRecommendItem;

/**
 * HpsVendorRecommendItemAction generated by GenCode.java
 */
public class HpsVendorRecommendItemAction extends BasisCrudAction<HpsVendorRecommendItem> {
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	public String edit() {
		if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			bean.setVendorSysid(getUserAccount().getSourceSysid());
			beaninfo.put("vendorSysid" + "Show",
					createDataDisplay(CpsVendor.class).get(getUserAccount().getSourceSysid()));
		}
		return super.edit();
	}
}