package tw.com.mitac.thp.action;

// Generated Sat Apr 02 15:03:24 CST 2016 by GenCode.java

import java.util.LinkedHashMap;

import tw.com.mitac.thp.bean.HpsVendorAp;
import tw.com.mitac.thp.bean.HpsVendorApDetail;

/**
 * HpsVendorApAction generated by GenCode.java
 */
public class HpsVendorApAction extends DetailController<HpsVendorAp> {
	@Override
	public LinkedHashMap<String, DetailInfo> getDetailInfoMap() {
		LinkedHashMap<String, DetailInfo> detailClassMap = super.getDetailInfoMap();
		detailClassMap.put("", new DetailInfo("", DETAIL_SET, "detail", HpsVendorApDetail.class));
		return detailClassMap;
	}
	
}