package tw.com.mitac.thp.action;

// Generated Sun Apr 17 10:42:07 CST 2016 by GenCode.java

import java.util.Date;
import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorCustomerService;

/**
 * HpsVendorCustomerServiceAction generated by GenCode.java
 */
public class HpsVendorCustomerServiceAction extends BasisCrudAction<HpsVendorCustomerService> {

	@Override
	protected QueryGroup getQueryRestrict() {
		Date date = new Date(systemDate.getTime() - (1000 * 60 * 60 * 24 * 3));
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			// 尚未回覆（無回覆日期）& 詢問日期在3天之前（超過3天）
			return new QueryGroup(new QueryRule("issueReplyDate", NU, null), new QueryRule("issueDate", LT, date));
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("issueReplyDate", NU, null), new QueryRule("issueDate", LT, date),
					new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			// addActionMessage("管理者可以查詢所有項目");
			addActionMessage("僅顯示超過3天尚未回覆的項目");
		}
		return super.main();
	}

	@Override
	protected boolean executeSave() {
		// 若有回覆內容＆無回覆日期
		if (StringUtils.isNotBlank(bean.getIssueReplyContent()) && bean.getIssueReplyDate() == null)
			bean.setIssueReplyDate(systemDate);

		return super.executeSave();
	}
}