package tw.com.mitac.thp.action;

import java.util.ArrayList;
import java.util.List;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorAdvertisement;

/**
 * HpsVendorAdvertisementAction generated by GenCode.java
 */
public class HpsVendorAdvertisementAction extends BasisCrudAction<HpsVendorAdvertisement> {
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	protected boolean executeSave() {
		// 檢核
		if (bean.getEndDate().compareTo(bean.getStartDate()) < 0) {
			addActionError("「結束日期」不可小於「起始日期」");
			return false;
		}

		// A.同一種廣告區塊(ADVERTISEMENT_TYPE), 起始日期與結束日期不可重疊
		List<QueryRule> queryRuleListA = new ArrayList<QueryRule>();
		queryRuleListA.add(new QueryRule(PK, NE, bean.getSysid())); // 不包含自己
		queryRuleListA.add(new QueryRule("vendorSysid", bean.getVendorSysid()));
		queryRuleListA.add(new QueryRule("advertisementType", bean.getAdvertisementType()));
		// B.邏輯：重疊的4種狀況
		// 1.起始日在DB的區間 : db.startDate <= startDate && startDate <= db.endDtae
		QueryGroup group1 = new QueryGroup(new QueryRule("startDate", LE, bean.getStartDate()), new QueryRule(
				"endDate", GE, bean.getStartDate()));
		// 2.結束日在DB的區間 : db.startDate <= endDate && endDate <= db.endDtae
		QueryGroup group2 = new QueryGroup(new QueryRule("startDate", LE, bean.getEndDate()), new QueryRule("endDate",
				GE, bean.getEndDate()));
		// 3.起始日～結束日在DB的區間內 : db.startDate <= startDate && endDate <= db.endDtae
		// 此邏輯已包含於 1 & 2 中，不實做
		// 4.DB的區間在起始日～結束日內 : startDate <= db.startDate && db.endDtae <= endDate
		QueryGroup group4 = new QueryGroup(new QueryRule("startDate", GE, bean.getStartDate()), new QueryRule(
				"endDate", LE, bean.getEndDate()));
		// B = (1 || 2 || 4)
		List<QueryGroup> groupList = new ArrayList<QueryGroup>();
		groupList.add(group1);
		groupList.add(group2);
		groupList.add(group4);
		QueryGroup queryGroupB = new QueryGroup(OR, null, groupList.toArray(new QueryGroup[0]));
		List<QueryGroup> queryGroupListB = new ArrayList<QueryGroup>();
		queryGroupListB.add(queryGroupB);
		// queryGroup = A && B
		QueryGroup queryGroup = new QueryGroup(AND, queryRuleListA.toArray(new QueryRule[0]),
				queryGroupListB.toArray(new QueryGroup[0]));
		// 查詢
		List<HpsVendorAdvertisement> adList = cloudDao.queryTable(sf(), HpsVendorAdvertisement.class, queryGroup,
				new QueryOrder[0], null, null);
		if (adList.size() > 0) {
			addActionError("同一廣告區塊在該時段已被「" + adList.get(0).getAdvertisementTitle() + "」使用，請挑選其它廣告區塊或起迄時間");
			return false;
		}

		String result = super.save();
		return super.executeSave();
	}
}