package tw.com.mitac.thp.action;

// Generated Wed May 04 09:42:36 CST 2016 by GenCode.java

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorNews;

/**
 * HpsVendorNewsAction generated by GenCode.java
 */
public class HpsVendorNewsAction extends BasisCrudAction<HpsVendorNews> {
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	public String edit() {
		// 預設值
		if (StringUtils.isBlank(bean.getSysid())) {
			if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType()))
				bean.setVendorSysid(getUserAccount().getSourceSysid());
		}

		String result = super.edit();
		return result;
	}

	@Override
	protected boolean executeSave() {
		if (StringUtils.isBlank(bean.getContent())) {
			addActionError("請填寫「內容」");
			return false;
		}
		if (bean.getEndDate().compareTo(bean.getStartDate()) < 0) {
			addActionError("「結束日期」不可小於「開始日期」");
			return false;
		}
		return super.executeSave();
	}
}