package tw.com.mitac.thp.action;

// Generated Thu Apr 14 13:17:55 CST 2016 by GenCode.java

import java.util.List;

import org.json.JSONObject;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorItem;
import tw.com.mitac.thp.bean.HpsVendorItemInspect;

/**
 * HpsVendorItemInspectAction generated by GenCode.java
 */
public class HpsVendorItemInspectAction extends BasisCrudAction<HpsVendorItemInspect> {
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("itemSysid", IN, getVendorItemIn()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String getActionTitle() {
		String result = super.getActionTitle();
		// 假欄位用MAP
		JSONObject jsonObject = new JSONObject(getConstantMenu().get("inspectType"));
		session.put("fakeMap", jsonObject.toString());
		return result;
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	protected String getVendorItemIn() {
		List<String> qList = (List<String>) cloudDao.findProperty(sf(), HpsVendorItem.class, new QueryGroup(
				new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0], false, "sysid");
		String itemIN = "*";
		for (String sysid : qList)
			itemIN += "," + sysid;
		return itemIN;
	}

	@Override
	protected boolean executeSave() {
		// setIsSnq 排序用
		String[] arr = bean.getInspectType().split(", ");
		bean.setIsSnq(false);
		for (String s : arr)
			if ("SNQ".equals(s))
				bean.setIsSnq(true);
		return super.executeSave();
	}
}