package tw.com.mitac.thp.action;

// Generated Sun Apr 17 10:42:07 CST 2016 by GenCode.java

import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorCustomerService;

/**
 * HpsVendorCustomerServiceAction generated by GenCode.java
 */
public class HpsVendorCustomerService2Action extends BasisCrudAction<HpsVendorCustomerService> {

	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("vendorSysid", getUserAccount().getSourceSysid()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	protected boolean executeSave() {
		// 若有回覆內容＆無回覆日期->壓上日期
		if (StringUtils.isNotBlank(bean.getIssueReplyContent()) && bean.getIssueReplyDate() == null)
			bean.setIssueReplyDate(systemDate);

		return super.executeSave();
	}
}