package tw.com.mitac.thp.action;

// Generated Tue Apr 12 20:43:55 CST 2016 by GenCode.java

import java.util.List;

import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryOrder;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.CpsEntity;
import tw.com.mitac.thp.bean.CpsVendor;
import tw.com.mitac.thp.bean.HpsVendorItem;
import tw.com.mitac.thp.bean.HpsVendorItemDetailType;

/**
 * HpsVendorItemDetailTypeAction generated by GenCode.java
 */
public class HpsVendorItemDetailTypeAction extends BasisCrudAction<HpsVendorItemDetailType> {
	@Override
	protected QueryGroup getQueryRestrict() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return QueryGroup.DEFAULT;
		} else if (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			return new QueryGroup(new QueryRule("itemSysid", IN, getVendorItemIn()));
		} else {
			return new QueryGroup(new QueryRule(PK, "x"));
		}
	}

	@Override
	public String main() {
		if (CpsEntity.class.getSimpleName().equals(getUserAccount().getSourceType())) {
			addActionMessage("管理者可以查詢所有項目");
		}
		return super.main();
	}

	@Override
	public String edit() {
		// if
		// (CpsVendor.class.getSimpleName().equals(getUserAccount().getSourceType()))
		// {
		// bean.setItemSysid(itemSysid);.setVendorSysid(getUserAccount().getSourceSysid());
		// beaninfo.put("vendorSysid" + "Show",
		// createDataDisplay(CpsVendor.class).get(getUserAccount().getSourceSysid()));
		// }
		return super.edit();
	}

	protected String getVendorItemIn() {
		List<String> qList = (List<String>) cloudDao.findProperty(sf(), HpsVendorItem.class, new QueryGroup(
				new QueryRule("vendorSysid", getUserAccount().getSourceSysid())), new QueryOrder[0], false, "sysid");
		String itemIN = "*";
		for (String sysid : qList)
			itemIN += "," + sysid;
		return itemIN;
	}
}