package tw.com.mitac.thp.action;

// Generated Mon Jul 18 17:54:18 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.MtsAppointmentCase;

/**
 * MtsAppointmentCaseAction generated by GenCode.java
 */
public class MtsAppointmentCaseAction extends BasisCrudAction<MtsAppointmentCase> {
}