package tw.com.mitac.thp.action;

// Generated Sat May 07 15:48:58 CST 2016 by GenCode.javaimport tw.com.mitac.hibernate.QueryGroup;
import org.apache.commons.lang3.StringUtils;

import tw.com.mitac.thp.bean.MtsAdsA;

/**
 * 館主用 MtsAdsAAction generated by GenCode.java
 */
public class MtsAdsAAction extends BasisCrudAction<MtsAdsA> {
	@Override
	public String[] getImgCols() {
		return new String[] { "adsImage" };
	}

	@Override
	protected boolean executeSave() {
		// 檢核
		String bannerType = bean.getBannerType();

		if ("V".equals(bannerType)) {
			if (StringUtils.isBlank(bean.getAdsUrl())) {
				addActionError("請輸入連結網址");
				return false;
			}
		}

		boolean result = super.executeSave();

		// 此檢核不能寫在存檔前，否則上傳圖片時會出錯，僅顯示訊息給USER看
		if ("P".equals(bannerType)) {
			if (StringUtils.isBlank(bean.getAdsImage())) {
				addActionError("貼心小提醒:您未上傳圖片");
			}
		}
		return result;
	}
}