package tw.com.mitac.thp.action;

// Generated Sat May 07 15:48:58 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.MtsArticleType;

/**
 * MtsArticleTypeAction generated by GenCode.java
 */
public class MtsArticleTypeAction extends BasisCrudAction<MtsArticleType> {
}