package tw.com.mitac.thp.action;

// Generated Mon May 09 13:20:23 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.MtsCollaborationFeedback;

/**
 * MtsCollaborationFeedbackAction generated by GenCode.java
 */
public class MtsCollaborationFeedbackAction extends BasisCrudAction<MtsCollaborationFeedback> {
	
}