package tw.com.mitac.thp.action;

// Generated Tue Mar 08 10:11:03 CST 2016 by GenCode.java

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.beanutils.PropertyUtils;
import org.apache.commons.lang3.StringUtils;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import tw.com.mitac.hibernate.DeleteStatement;
import tw.com.mitac.hibernate.QueryGroup;
import tw.com.mitac.hibernate.QueryRule;
import tw.com.mitac.thp.bean.BhsAdsC;
import tw.com.mitac.thp.bean.MtsCooperation;
import tw.com.mitac.thp.bean.MtsHighlight;
import tw.com.mitac.thp.bean.MtsProducts;
import tw.com.mitac.thp.bean.MtsRecommand;
import tw.com.mitac.thp.bean.MtsRecommandItem;
import tw.com.mitac.thp.bean.MtsVendorProfile;
import tw.com.mitac.thp.util.Util;

/**
 * MtsRecommandAction generated by GenCode.java
 */
public class MtsRecommandAction extends DetailController<MtsRecommand> {

	@Override
	public LinkedHashMap<String, DetailInfo> getDetailInfoMap() {
		LinkedHashMap<String, DetailInfo> detailClassMap = super.getDetailInfoMap();
		detailClassMap.put("", new DetailInfo("", DETAIL_SET, "detail", MtsRecommandItem.class));
		return detailClassMap;
	}

	/**
	 * [jqgrid]
	 */
	public Map<String, Map> getJqgridDetailColModelInfoMap() {
		Map<String, Map> jqgridDetailColModelInfoMap = super.getJqgridDetailColModelInfoMap();
		Map<String, Map> jqgridDetailColModelMap = jqgridDetailColModelInfoMap.get("");
		Map<String, Object> colModelMap = jqgridDetailColModelMap.get("sourceSysid");
		Map<String, Object> editoptionsMap = (Map<String, Object>) colModelMap.get("editoptions");
		// Map<String, Object> searchoptionsMap = (Map<String, Object>)
		// colModelMap.get("searchoptions");

		Class<?> targetClass = null;
		if ("T".equalsIgnoreCase(bean.getRecommandType())) {
			targetClass = MtsVendorProfile.class;
		} else if ("S".equalsIgnoreCase(bean.getRecommandType())) {
			targetClass = MtsProducts.class;
		} else if ("H".equalsIgnoreCase(bean.getRecommandType())) {
			targetClass = MtsHighlight.class;
		} else if ("I".equalsIgnoreCase(bean.getRecommandType())) {
			targetClass = MtsCooperation.class;
		}

		if (targetClass != null) {
			colModelMap.put("selectTool", targetClass.getSimpleName());
			Map<String, String> editoptionsValueMap = createDataDisplay(targetClass);
			editoptionsMap.put("value", editoptionsValueMap);
			// colModelMap.put("stype", "select");
			colModelMap.put("formatter", "select");
		}
		return jqgridDetailColModelInfoMap;
	}

	@Override
	protected boolean executeSave() {
		// remap order
		Set<MtsRecommandItem> detailSet = (Set<MtsRecommandItem>) sessionGet(DETAIL_SET);
		if (detailSet != null) {
			List<MtsRecommandItem> list = new ArrayList<MtsRecommandItem>(detailSet);
			Collections.sort(list, new Comparator<MtsRecommandItem>() {
				public int compare(MtsRecommandItem ent1, MtsRecommandItem ent2) {
					return (ent1.getDataOrder().compareTo(ent2.getDataOrder()));
				}
			});
			int order = 1;
			for (MtsRecommandItem detail : list) {
				detail.setDataOrder(order);
				order++;
			}
			detailSet = new LinkedHashSet<MtsRecommandItem>(list);
			sessionSet(DETAIL_SET, detailSet);
		}

		return super.executeSave();
	}

	// 尾檔完成（替代刪除事件
	public String ajaxLoadComplete() {
		String msg = SUCCESS;
		try {
			String parentSysid = request.getParameter("parentSysid");
			if (StringUtils.isBlank(parentSysid)) {
				resultString = "參數錯誤";
				return JSON_RESULT;
			}
			int total = cloudDao.queryCount(sf(), MtsRecommandItem.class,
					new QueryGroup(new QueryRule(FK, parentSysid)));

			// remap order
			Set<MtsRecommandItem> detailSet = (Set<MtsRecommandItem>) sessionGet(DETAIL_SET);
			if (detailSet == null)
				detailSet = new LinkedHashSet<MtsRecommandItem>();
			if (detailSet.size() != total) {
				List<MtsRecommandItem> list = new ArrayList<MtsRecommandItem>(detailSet);
				Collections.sort(list, new Comparator<MtsRecommandItem>() {
					public int compare(MtsRecommandItem ent1, MtsRecommandItem ent2) {
						return (ent1.getDataOrder().compareTo(ent2.getDataOrder()));
					}
				});
				int order = 1;
				for (MtsRecommandItem detail : list) {
					detail.setDataOrder(order);
					order++;
				}
				detailSet = new LinkedHashSet<MtsRecommandItem>(list);
				sessionSet(DETAIL_SET, detailSet);

				MtsRecommand newBean = (MtsRecommand) cloudDao.get(sf(), MtsRecommand.class, parentSysid);
				newBean.setDetailSet(detailSet);
				List<Object> saveDetailList = new ArrayList<Object>();
				saveDetailList.add(newBean);
				msg = cloudDao.save(sf(), saveDetailList.toArray(), false, null);
				if (!SUCCESS.equals(msg)) {
					resultString = msg;
					return JSON_RESULT;
				} else {
					List<Object> deleteDetailList = new ArrayList<Object>();
					deleteDetailList.add(new DeleteStatement(MtsRecommandItem.class.getSimpleName(),
							new QueryGroup(new QueryRule(FK, NU, ""))));
					msg = cloudDao.save(sf(), deleteDetailList.toArray(), false, null);
					if (!SUCCESS.equals(msg)) {
						resultString = msg;
						return JSON_RESULT;
					} else {
						msg = "reloadGrid";
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			resultString = "尾檔排序發生錯誤";
			return JSON_RESULT;
		}
		resultString = msg;
		return JSON_RESULT;
	}

	// 尾檔新增or更新
	public String ajaxDetailSave() {
		String msg = SUCCESS;
		try {
			String sysid = request.getParameter("sysid");
			String newIds = request.getParameter("dataOrder");
			String parentSysid = request.getParameter("parentSysid");
			String sourceSysid = request.getParameter("sourceSysid");
			String remark = request.getParameter("remark");
			if (sysid == null || StringUtils.isBlank(newIds) || StringUtils.isBlank(parentSysid)) {
				resultString = "尾檔排序參數錯誤";
				return JSON_RESULT;
			}
			int newOrder = Integer.parseInt(newIds);

			Boolean isNew = true;
			MtsRecommandItem detailBean;
			if (StringUtils.isNotBlank(sysid)) {
				detailBean = (MtsRecommandItem) cloudDao.get(sf(), MtsRecommandItem.class, sysid);
				isNew = false;
			} else {
				detailBean = new MtsRecommandItem();
				Util.defaultPK(detailBean);
				detailBean.setParentSysid(parentSysid);
				detailBean.setDataOrder(newOrder);
				detailBean.setSourceSysid(sourceSysid);
				detailBean.setRemark(remark);
			}

			int total = cloudDao.queryCount(sf(), MtsRecommandItem.class,
					new QueryGroup(new QueryRule(FK, parentSysid)));
			if (isNew) {
				if (newOrder < (total + 1)) {
					// upper
					msg = shiftDetailOrder(parentSysid, newOrder, total, 1);
				} else if (newOrder > (total + 1)) {
					detailBean.setDataOrder(total + 1);
				}
			} else {
				int oldOrder = detailBean.getDataOrder();
				detailBean.setDataOrder(newOrder);
				if (newOrder < oldOrder) {
					// upper
					msg = shiftDetailOrder(parentSysid, newOrder, oldOrder - 1, 1);
				} else if (newOrder > oldOrder) {
					// downer
					msg = shiftDetailOrder(parentSysid, oldOrder + 1, newOrder, -1);
					if (newOrder > total) {
						detailBean.setDataOrder(total);
					}
				}
			}

			defaultValue(detailBean);
			List<Object> saveDetailList = new ArrayList<Object>();
			saveDetailList.add(detailBean);
			msg = cloudDao.save(sf(), saveDetailList.toArray(), false, null);
			if (!SUCCESS.equals(msg)) {
				resultString = msg;
				return JSON_RESULT;
			}

			MtsRecommand newBean = (MtsRecommand) cloudDao.get(sf(), MtsRecommand.class, parentSysid);
			sessionSet(DETAIL_SET, newBean.getDetailSet());
		} catch (Exception e) {
			e.printStackTrace();
			resultString = "尾檔排序發生錯誤";
			return JSON_RESULT;
		}
		resultString = msg;
		return JSON_RESULT;
	}

	// 尾檔拖拉排序
	public String ajaxDetailSoab() {
		String msg = SUCCESS;
		try {
			String sysid = request.getParameter("sysid");
			String newIds = request.getParameter("newIds");
			String parentSysid = request.getParameter("parentSysid");
			if (StringUtils.isBlank(sysid) || StringUtils.isBlank(newIds) || StringUtils.isBlank(parentSysid)) {
				resultString = "尾檔排序參數錯誤";
				return JSON_RESULT;
			}
			int newOrder = Integer.parseInt(newIds);

			MtsRecommandItem deatilbean = (MtsRecommandItem) cloudDao.get(sf(), MtsRecommandItem.class, sysid);
			int oldOrder = (int) PropertyUtils.getProperty(deatilbean, DATA_ORDER);
			if (newOrder < oldOrder) {
				// upper
				msg = shiftDetailOrder(parentSysid, newOrder, oldOrder - 1, 1);
			} else if (newOrder > oldOrder) {
				// downer
				msg = shiftDetailOrder(parentSysid, oldOrder + 1, newOrder, -1);
			}
			if (!SUCCESS.equals(msg)) {
				resultString = msg;
				return JSON_RESULT;
			}

			PropertyUtils.setProperty(deatilbean, DATA_ORDER, newOrder);
			defaultValue(deatilbean);
			List<Object> saveDetailList = new ArrayList<Object>();
			saveDetailList.add(deatilbean);
			msg = cloudDao.save(sf(), saveDetailList.toArray(), false, "UPDATE");
			if (!SUCCESS.equals(msg)) {
				resultString = msg;
				return JSON_RESULT;
			}

			MtsRecommand newBean = (MtsRecommand) cloudDao.get(sf(), MtsRecommand.class, parentSysid);
			sessionSet(DETAIL_SET, newBean.getDetailSet());
		} catch (Exception e) {
			e.printStackTrace();
			resultString = "尾檔排序發生錯誤";
			return JSON_RESULT;
		}
		resultString = msg;
		return JSON_RESULT;
	}

	protected String shiftDetailOrder(String parentSysid, int startIdx, int endIdx, int shiftNum) {
		try {
			// HQL
			Session session = sf().openSession();
			Transaction tx = session.beginTransaction();
			String tableName = MtsRecommandItem.class.getSimpleName(); // getPersistentClass().getSimpleName();
			String columnName = "dataOrder";
			String qStr = "UPDATE " + tableName + " ";
			qStr += "SET " + columnName + " = " + columnName + " ";
			if (shiftNum >= 0)
				qStr += "+ ";
			qStr += shiftNum + " ";
			qStr += "WHERE " + columnName + " >= " + startIdx + " ";
			qStr += "AND " + columnName + " <= " + endIdx + " ";
			qStr += "AND " + FK + " = '" + parentSysid + "' ";
			Query query = session.createQuery(qStr);
			query.executeUpdate();
			tx.commit();
			session.close();
		} catch (Exception e) {
			e.printStackTrace();
			return "排序發生錯誤";
		}
		return SUCCESS;
	}

	public String aPluralityOfData() {
		String msg = SUCCESS;
		String myarr = request.getParameter("myarr");

		logger.debug("資料導入：" + myarr);
		String[] pluralitySysid = myarr.split(",");

		
		for (int i = 0; i < pluralitySysid.length; i++) {
			logger.debug("處理後值：" + pluralitySysid[i]);

			Set<MtsRecommandItem> dataSet = (Set<MtsRecommandItem>) findDetailSetWhenEdit(DETAIL_SET);
			
			MtsRecommandItem item = getDefaultDMO(MtsRecommandItem.class);

			item.setParentSysid(bean.getSysid());
			item.setSourceSysid(pluralitySysid[i]);
			item.setDataOrder(1);
			defaultValue(item);
			tw.com.mitac.thp.util.Util.defaultPK(item);
			dataSet.add(item);
		}

		remapDataOrder(DETAIL_SET);

		resultString = msg;
		return JSON_RESULT;
	}

}