package tw.com.mitac.thp.action;

// Generated Sat May 07 15:48:58 CST 2016 by GenCode.java

import tw.com.mitac.thp.bean.MtsRecommandItem;

/**
 * MtsRecommandItemAction generated by GenCode.java
 */
public class MtsRecommandItemAction extends BasisCrudAction<MtsRecommandItem> {
}